### ISSUE TITLE
Fjerne questback-undersøkelse

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-portal#1013]
Undersøkelsen basert på questback er over, så vi kan fjerne denne frå portal. 

Det vil vere ein fordel om vi "tar vare på" koden, slik at det er fort gjort å slå på tilsvarande undersøking i framtida.

**Comment by AinaEngen** [comment]
@stigbd - sjekke når denne skal fjernes

**Comment by stigbd** [comment]
Iflg følgande post i datalandsbyen skal undersøkelsen avsluttast 1. september:
https://datalandsbyen.norge.no/topic/219/brukerunders%C3%B8kelse-p%C3%A5-data-norge-no

**Comment by oyvindis** [comment]
Når denne skal fjernes, f.eks. gjør en "revert" av commit som la den til: https://github.com/Informasjonsforvaltning/fdk-portal/commit/a7480ee3e263236668f69cdec964faf3c4cd31b1

**Comment by joachim-me** [comment]
Ja, utført. Lukker saken.
