### ISSUE TITLE
Legge til @opnedata til twitter-embeddingen i portal

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#1051]
Ref behov: https://github.com/Informasjonsforvaltning/behov/issues/140
Se design: https://eggedosis.github.io/fdk-design/redirects/portal/home/home-default.html

https://twitter.com/opnedata

![image](https://user-images.githubusercontent.com/73637969/134494579-26d9e6ca-fc75-4545-8b91-2420ff708112.png)

**Comment by LeneSundsbo** [comment]
@shenluna  [Her er lenke til design](https://eggedosis.github.io/fdk-design/redirects/portal/home/home-default.html). Hele venstrespalten er redesignet.

**Comment by shenluna** [comment]
Etter nytt design utgår twitter da det heller ikke blir nevneverdig brukt. Lukker derfor denne saken.
