### ISSUE TITLE
Fremheve APIer som er relatert til datasett

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#1116]
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/635

APIer som relaterer til et datasett blir per dags dato lagt under "Andre som relaterer til dette datasettet" da det er en enveis relasjon fra API til datasett. Denne relasjonen må løftes og vi ønsker nå å legge det under fanen som i dag heter Distribusjoner. Vi ønsker å endre tittel fra "Distribusjoner" til "Distribusjoner og Datatjenester", APIer som relaterer til datasettet skal legges øverst i denne listen.

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-default.html

**Comment by oystein-asnes** [comment]
Foreslår å slå sammen `distribusjoner `og `datatjenester `under samme overskrift - ikke minst fordi en datatjeneste både kan relateres direkte til datasettet (dcat:servesdatasett) eller (men også i tillegg... )  fra en tilknyttet distribusjon (dcat:accessService). 
Overskrift: "Distribusjoner og datatjenester" 

1. Når en distribusjon har oppgitt dcat:accessService --> legg på API-ikonet i tillegg til format
2. Når en datatjeneste er knyttet direkte til datasettet --> samme som over

Når en klikker på 1. så kommer brukeren inn i API-katalogens detaljvisning. Når en klikker på 2. ekspanderer distribusjonen og viser detaljer om distribusjonen. `Datatjeneste`  er en av disse detaljelementene. 

Modellen slik den ser ut i standarden:
![image](https://user-images.githubusercontent.com/11029809/146950959-b0ba973c-de93-4e0b-b6cf-0d9d2022c362.png)

**Comment by oystein-asnes** [comment]
Obs. Fikk en følelse av å hå skrevet noe lignende et annet sted. Denne burde merges med https://github.com/Informasjonsforvaltning/behov/issues/635 @shenluna

**Comment by shenluna** [comment]
Prodsatt og verifisert i både data.norge og datafabrikken
