### ISSUE TITLE
Alle driftsmeldinger regnes som aktive

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-portal#1143]
![image](https://user-images.githubusercontent.com/8625716/150352643-ba9206e2-b7af-4510-869d-ea6eb6c9790d.png)

**Comment by shenluna** [comment]
Dette er nå fikset og prodsatt.
Aktive driftsmeldinger vises under:
![image](https://user-images.githubusercontent.com/73637969/151541142-76a9fcd3-f94d-4a1b-8e16-19587c91b259.png)

Ved trykk på "Vis alle" vil man kunne se alle tidligere driftsmeldinger.
