### ISSUE TITLE
Bruk environment og channel_publiseringportal til service messages

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-portal#1152]
https://github.com/Informasjonsforvaltning/fdk-cms-service/issues/63

**Comment by KurtStian** [comment]
Testet OK at driftsmelding blir publisert på publiseringsportalen i miljøet staging når det er valgt channel publiseringsportal og miljø staging.
Men på samlesiden for driftsmeldinger på staging blir ikke driftsmeldingen tagget med Publiseringsportalen. (kanskje ikke imp. ennå).

**Comment by shenluna** [comment]
Testet OK, lukker dermed saken
