### ISSUE TITLE
Organisasjons navn vises ikke i valgt språk

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#1163]
Eks, hvis man har valgt engelsk står organisasjonsnavnet på bokmål

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/2222a4ee-fc69-4edd-af8f-7050a932cbd0)

Se mer i kommentarene i dette issuet: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/528

**Comment by stigbd** [comment]
528 som det referers til har ingenting med dette å gjere, slik eg ser det. 
Dette issuets root cause er at organziaion-catalog, som har informasjon om organisasjons-navn, ikkje har navn på engelsk:
```
% curl https://organization-catalogue.staging.fellesdatakatalog.digdir.no/organizations/991825827 | jq
{
  "organizationId": "991825827",
  "norwegianRegistry": "https://data.brreg.no/enhetsregisteret/api/enheter/991825827",
  "name": "DIGITALISERINGSDIREKTORATET",
  "orgType": "ORGL",
  "orgPath": "/STAT/972417858/991825827",
  "subOrganizationOf": "972417858",
  "issued": "2007-10-15",
  "municipalityNumber": "0301",
  "industryCode": "84.110",
  "sectorCode": "6100",
  "prefLabel": {
    "nb": "Digitaliseringsdirektoratet"
  },
  "orgStatus": "NORMAL",
  "homepage": "www.digdir.no"
}
```

**Comment by stigbd** [comment]
For at navn skal vises på andre språk, må organization-catalog oppdateres. P.t. har vi ingen (god) løype for dette.

**Comment by shenluna** [comment]
Basert på kommentarer over lukker vi denne saken på nåværende tidspunkt. Dette vil bli tatt opp igjen hvis behovet melder seg.
