### ISSUE TITLE
Legge til støtte for nedlasting og forhåndsvisning av eksempeldata

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-portal#1196]

**Comment by oystein-asnes** [comment]
Eksempeldata kan dekke ulike behov: 

1. Datasettet inneholder personopplysninger og har dermed ingen allment tilgjengelige  distribusjoner. Tilbyder ønsker å vise et anonymisert uttrekk med en eller flere rader som en del av beskrivelsen.
2. Datasettet kan deles åpent men det er ikke publisert ennå og ingen distribusjoner eksisterer. Tilbyder ønsker likevel å tilby eksempeldata som viser noen rader .
3. Tilbyder har et API og har registrert dette som en tilhørende datatjeneste, men vil tilby eksempeldata med noen rader i tabellform som en mer menneskelesbar representasjon av data og/eller fordi API krever en API-nøkkel.


Eksempeldatas forhold til vanlige distribusjoner og datatjenester:
- Eksempeldata er metadata. Formålet er å vise struktur.
- Eksempeldata kan komme i tillegg til "vanlige" distribusjoner og datatjenester ELLER stå alene.
- Eksempeldata kan potensielt ha alle opplysninger som er knyttet til klassen `dcat:distribution`, men de mest sentrale opplysningene er `beskrivelse`, `format`, `tilgangslenke`, og `nedlastingslenke`.

Eksempeldata er omtalt her https://data.norge.no/guide/veileder-beskrivelse-av-datasett/#datasett-eksempeldata
