### ISSUE TITLE
demo.fellesdatakatalog.brreg.no "Vi har flyttet" skal peke mot demo

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#120]
Når bruker er i demo-løsningen, skal denne også peke mot ny demoløsning.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/cc1db9d0-79a3-4441-b7cf-012d41b7aa8f)

**Comment by valosnah** [comment]
Fix'd

**Comment by lillelars** [comment]
fungerer nå som forventet
