### ISSUE TITLE
Informasjonsmodellen Restanser API gir feilmelding

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#1214]
https://data.norge.no/informationmodels/b3a030db-390e-3eca-a128-8a25fca4fae1

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/c9d8a7e8-2659-4bfe-8952-bf09d7eac4d6)

![image](https://user-images.githubusercontent.com/73637969/165244131-5cd7dcfe-d691-4f0f-9e3d-1fca1d978884.png)

**Comment by valosnah** [comment]
> 2022-04-26 10:03:53.650 CEST
Minified React error #152; visit [](https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=g) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Hvis man går til error #152:
The full text of the error you just encountered is:
g(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

**Comment by valosnah** [comment]
@oyvindis Kallet ser ut til å gå helt fint bakover i stacken. Ser ut som noe i fdk-portal brekker?
