### ISSUE TITLE
Informasjonsmodell som ikke vil laste inn - demo

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-portal#1222]
Fanget opp vha frontend_alerts.

Siden for en informasjonsmodell blir ikke lastet inn.
Lignende oppførsel som vi har sett nylig, der siden synes i et brøkdels sekund, før portal hopper til 404.

https://demo.fellesdatakatalog.digdir.no/informationmodels/55ee3706-301d-4223-a514-ce3f0385aad9

**Comment by oyvindis** [comment]
Finner ingen informasjonsmodell med denne id, så antar noen kanskje har testet en gammel lenke som ikke fungerer lenger. Feilmeldingen er at informasjonsmodellen ikke finnes, det stemmer nok.
