### ISSUE TITLE
Informasjonssider om katalogene

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#1240]
- [x] Datasettkatalogen
- [x] Begrepskatalogen
- [x] API-katalogen
- [x] Informasjonsmodellkatalogen

Se design: https://www.figma.com/proto/pnrNm7VYrlPv5cCrurdWLj/Min-FDK?page-id=0%3A1&node-id=721%3A103669&viewport=-632%2C-383%2C0.06&scaling=scale-down-width&starting-point-node-id=706%3A101040&show-proto-sidebar=1

**Comment by joachim-me** [comment]
Løst
