### ISSUE TITLE
Kun tekst i nedfallsmenyen er klikkbar

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1265]
Kun teksten, og ikke hele det gråskraverte området, er klikkbart i knappene i nedfallsmenyen.

![bilde](https://user-images.githubusercontent.com/108797958/183863755-924ede43-cc75-4b88-8422-442e45183265.png)

**Comment by KjerstiSteien** [comment]
@AinaEngen og @jeffreiffers Er dette noe som er løst/under arbeid, eller kan jeg sette saken til Ready?

**Comment by AinaEngen** [comment]
Retestet i Staging, og der kan man klikke i hele feltet. Denne kan derfor lukkes
