### ISSUE TITLE
Default-bilde

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-portal#1270]
Mangel på defaultbilde fører til masse ledig rom i "Aktuelt"-siden.

![news.png](https://images.zenhubusercontent.com/621e2fbb9626c4acaf8af241/2cd1bf17-5542-4be2-b12e-93a52bdb4c40)

**Comment by LeneSundsbo** [comment]
Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/article/articles-all.html

**Comment by joachim-me** [comment]
Vi må se på hele Aktuelt-siden på nytt.
