### ISSUE TITLE
fdk-portal bruker utdatert oidc pakke

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-portal#1301]
oidc-client fungerer ikke med ny versjon av keycloak, bør endre til feks keycloak-js versjon 19.0.2

**Comment by joachim-me** [comment]
@NilsOveTen Fortsatt aktuell?

**Comment by NilsOveTen** [comment]
ja, ref: https://github.com/Informasjonsforvaltning/fdk-portal/blob/develop/package.json#L96

burde bruke denne: https://www.npmjs.com/package/keycloak-js
Da med samme versjon vi bruker av keycloak, som atm er 19.0.2

**Comment by jeffreiffers** [comment]
Portal har siste versjon 1.11.5. Vi bør kanskje forsøke å inn oidc-client i registreringsløsningen. Logout er fikset i portalen.

**Comment by NilsOveTen** [comment]
Ja, siden logout nå fungerer er ikke denne aktuell. Lukker
