### ISSUE TITLE
WCAG - For lav kontrast brukernavn og ikon fra datalandsbyen

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-portal#1302]
![image](https://user-images.githubusercontent.com/430997/192777610-5f57923c-271e-4930-85da-ffd397dd4979.png)

**Comment by LeneSundsbo** [comment]
@jeffreiffers
I know. Dette er farger hentet direkte fra NodeBB, og dermed ikke noe vi styrer. Men jeg har laget forslag til nye farger, så hvis de kan byttes ut er jeg klar. (Penere blir det også…)

**Comment by jeffreiffers** [comment]
Fargen blir valgt av NodeBB. Ser ikke noe enkel måte å endre logikken. Hvordan har du tenkt å løse det?

**Comment by LeneSundsbo** [comment]
@jeffreiffers 
Kan vi overstyre farge på teksten til å være neutral-60? Ser ut til at det er gjort på [sider for innlegg](https://datalandsbyen.norge.no/topic/211/norske-str%C3%B8mpriser/3).

Så lenge navnet overholder kontrastkrav og dermed er lesbart, så trenger ikke ikonet å behandles like strengt. Det er fint å benytte farge på ikonet for å skille mellom brukere.
