### ISSUE TITLE
Datalandsbyen posts - håndtere mulig bilder og kildekode

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-portal#1309]

**Comment by joachim-me** [comment]
@jeffreiffers Kan du beskrive denne saken?

**Comment by terjesyl** [comment]
@jeffreiffers kan du beskrive saken, ev. finne eksempel på feilen?

**Comment by KjerstiSteien** [comment]
Lukkes da vi ikke har nok info om hva saken handler om.
