### ISSUE TITLE
WCAG - Tekst "beta" er for liten

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-portal#1310]
![image](https://user-images.githubusercontent.com/430997/193255537-fa8798c4-4263-4108-9a8d-32337ea118e0.png)

**Comment by LeneSundsbo** [comment]
@jeffreiffers Hva er minimum font size?
Trodde 14 px var ok 🤔 Googler, men finner ikke svaret.

**Comment by jeffreiffers** [comment]
Font på nettsiden er ikke 14 men 10px. Alt lik eller under 10px er for liten.

**Comment by LeneSundsbo** [comment]
Ok. Da synes vi skal gå for 14px 👍🏻
