### ISSUE TITLE
WCAG - Kontrastfeil virksomhetssiden

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-portal#1311]
![image](https://user-images.githubusercontent.com/430997/193262482-4ea9b7eb-9570-426b-99a7-bbf25f91222b.png)

**Comment by LeneSundsbo** [comment]
Dette løses når vi oppdaterer denne siden med de nye ikonene. @pooriamehregan har fått det siste ikonet som trengs til denne sien.

**Comment by jeffreiffers** [comment]
Er det kun ikonene som endres eller også backgrunnsfargene/tekstfargene?

**Comment by LeneSundsbo** [comment]
Kun ikonene skal være nok.

**Comment by LeneSundsbo** [comment]
Strekfarger for katalog-ikoner:
Datasett blue-60
API/datatjeneste brown-60
Begrep green-60
Infomod puple-60
Tjenester red-60
