### ISSUE TITLE
WCAG - Kontrastfeil filter

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-portal#1316]
![image](https://user-images.githubusercontent.com/430997/193527317-64deb09b-3d00-4cb7-a090-e5f46c281a4a.png)

**Comment by LeneSundsbo** [comment]
@jeffreiffers 
Farge på knapp endres til neutral-60.

**Comment by jeffreiffers** [comment]
Vi ønsker vel ikke vise det som en knapp. Skulle vi ikke bare endret tekstfargen på knappen?

**Comment by jeffreiffers** [comment]
For såvidt jeg vet kan vi bare endre tekstfargen og ikke selve knappen. Vi ønsker vel ikke vise dette som en knapp.

**Comment by LeneSundsbo** [comment]
Ja, endre farge på teksten. (Som per def. er en knapp siden den har en funksjon 🙃)
