### ISSUE TITLE
Side for teknisk feil: Oppdatere design

### ISSUE THREAD

**Issue by tenstad** [Informasjonsforvaltning/fdk-portal#1320]
@LeneSundsbo commented on [Tue Oct 04 2022](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/636)

Følgende oppdateringer er ønskelig:
- All brødtekst på én og samme linje.
- Fjerne dekorstripene nederst i skjermbildet.
- Erstatte stripene øverst med ny fil (vedlagt)

[Designskisser for mobil](https://eggedosis.github.io/fdk-design/redirects/portal/other/500-m.html)
[Designskisser for desktop](https://eggedosis.github.io/fdk-design/redirects/portal/other/500.html)

![illustration-lines-corner.svg](https://images.zenhubusercontent.com/5d5bd38ecce8ee0649bb1a75/6f5e7482-9ec5-45f2-bc25-66328505b29d)

**Comment by tenstad** [comment]
@LeneSundsbo kan du exporte den svgen rett fra kilden og sende meg på slack?

**Comment by tenstad** [comment]
ev. bare push rett på denne branchen: https://github.com/Informasjonsforvaltning/fdk-portal/tree/fix/at/error-page

**Comment by joachim-me** [comment]
@tenstad Hvor står denne saken?
