### ISSUE TITLE
Feil i relaterte ressursar i datasettkatalogen

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/fdk-portal#1345]
Relasjonar mellom datasett ser grisete ut i frontend. I staden for å vise ressursane som det er relatert til, spyr vi ut internte urlar frå registreringsløysinga:  
Sjå https://data.norge.no/datasets/5f41f578-2841-3c74-92dc-6a3db859ec16 og https://data.norge.no/datasets/d136f2f6-a62e-373b-9337-77407a07b647
![Skjermbilde 2022-10-21 145157](https://user-images.githubusercontent.com/11029809/197200193-2f9cf259-6034-4943-9276-8d70d2077bd4.png)

**Comment by KjerstiSteien** [comment]
Verifisert løst av @oystein-asnes
