### ISSUE TITLE
Venstremeny blir smalere når man scroller

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-portal#1346]
Se https://data.norge.no/datasets/5f41f578-2841-3c74-92dc-6a3db859ec16

**Comment by KjerstiSteien** [comment]
@jeffreiffers er denne løst nå?

**Comment by jeffreiffers** [comment]
Nei

**Comment by KjerstiSteien** [comment]
Skal jeg flytte den til ready, eller er det noe du ønsker å jobbe videre på?
