### ISSUE TITLE
[Tjeneste] Komponenten Relaterte hendelser

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1371]
Tilsvarer `cv:isGroupedBy` i CPSV og feltet `isGroupedBy` i JSON-responsen fra backend.

Legg til "Inngår i" i tekstfelt og translations.

![bilde](https://user-images.githubusercontent.com/108797958/205893554-c2005886-fb4d-4190-b1e4-f437159780d5.png)

Depends on
- [x] #1362 
- [x] #1367 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/178

**Comment by hegeaal** [comment]
@KurtStian Hva tenker du er oversettelsen på engelsk (og evt. nynorsk) for "inngår i"?

**Comment by BRespen** [comment]
Støtter "included in" og "inngår i"
