### ISSUE TITLE
[Tjeneste] Komponenten Deltakende

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1373]
Tilsvarer aktører knyttet til `cv:hasParticipation` i CPSV. Ligger på feltet `participatingAgents` i JSON-respons.

- [x] Endre label fra "deltagende" til "deltakende".

- [x] Navn på aktør: `title`
- [x] Aktørtype: ligger under `orgType` (som er av typen [ReferenceDataCode](https://github.com/Informasjonsforvaltning/fdk-rdf-parser/blob/e693b6d382241a96efdc009ddb0a47cf5f0b8d40/src/fdk_rdf_parser/classes/reference_data_code.py#L9)) (eksempel Nasjonal Myndighet), bruk `prefLabel` (locale/lang string)
- [x] Listevisning med entry for hver aktør
  - [x] Vise dekningsområde (`spatial` fra dct:spatial)
  - [x] Vise hjemmeside (`homepage`)
  - [ ] VIse roller (fra Participation-objekter i `playsRole`)
     - Er en liste av [Participation-objekter](https://github.com/Informasjonsforvaltning/fdk-rdf-parser/blob/e693b6d382241a96efdc009ddb0a47cf5f0b8d40/src/fdk_rdf_parser/classes/participation.py#L12). Bruk `role` som peker til [SkosConcept-objekt](https://github.com/Informasjonsforvaltning/fdk-rdf-parser/blob/e693b6d382241a96efdc009ddb0a47cf5f0b8d40/src/fdk_rdf_parser/classes/skos_concept.py#L10). Bruk `prefLabel` derifra.
  - [ ] Vise beskrivelse av rolle (fra Participation.description i `playsRole`), bruk `description`-feltet.

![bilde](https://user-images.githubusercontent.com/108797958/205897256-61cc92d0-3738-4915-9375-06330b6d6c1d.png)

Depends on
- [x] #1364
- [x] #1362 
- [x] #1363 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/175

**Comment by terjesyl** [comment]
@KurtStian @BRespen Hvor skal lenken peke til ("[Skatteetaten]()" i eksempelet over)?

**Comment by KurtStian** [comment]
@terjesyl  Den peker nok til organization-catalog. Eksempel på at det finnes organisasjonsnummer som vi kan bruke.
Mener å huske at Politiet er et eksempel på når det ikke finnes org.nr, samt bruk av preflabel der preflabel og navn er ulik.

**Comment by terjesyl** [comment]
Feltet for beskrivelse av rolle må oppdateres (må avklare først hva vi skal støtte i forhold til spec'en).
I eksempelet i staging (se bilde) skal teksten være
```
| (Venstrekolonne) | (Høyrekolonne)                         |
| Dataleverandør   | Deltagelse med rollen 'datatilbyder'.  |
```

Data i venstrekolonne `participatingAgents[n].role[n].prefLabel[lang]` og data fra høyrekolonnen er fra `participatingAgents[n].description[lang]` og 

![bilde](https://user-images.githubusercontent.com/108797958/218676995-6a958cc7-16dd-4851-b1c9-a1c60faf4465.png)
