### ISSUE TITLE
[Tjeneste] Komponenten Regel

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1374]
Tilsvarer `cpsv:Rule` og `follows` i JSON-responsen.

Trenger `cpsv:implements` fra backend.

Regel vises dersom navn eller beskrivelse fins.

- [ ] Liste for visning av Regler
- [ ] Visning av hver regel
  - [ ] Navn: `name`
  - [ ] Beskrivelse: `description`
  - [ ] Tilgjengelige språk: `language`
  - [ ] Har bakgrunn i: `cpsv:implements`

![bilde](https://user-images.githubusercontent.com/108797958/205921305-62e1cab9-eaf0-4a82-a28e-70a75582010c.png)

Depends on
- [x] #1364
- [x] #1362 
- [x] #1363 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/173

**Comment by terjesyl** [comment]
@KurtStian Ser at navn og beskrivelse er obligatorisk i specen. Hva er minimumsinfo vi trenger før vi viser en Regel? Hvis f.eks. navn mangler, men det er en beskrivelse, skal vi da vise det? Og hva hvis det kun er navn og ingenting annet?

**Comment by KurtStian** [comment]
Ja, jeg tenker at vi kan vise en regel kun med beskrivelse eller navn. I en ev. registreringsløsning vil dette ikke være mulig å publisere, men ved høsting er det jo (i hvert fall foreløpig) ingen sjekk som avviser høsting/publisering av informasjonsgrupper (klasser) som mangler obligatoriske informasjon, tror jeg...
