### ISSUE TITLE
[Tjeneste] Komponenten Relatert regelverk

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1375]
Tilsvarer: `cpsv:hasLegalResource` og `hasLegalResource` i JSON-respons.

- [ ] Liste for visning av flere entries
- [ ] Visning av Regelverk/LegalResource (alle felter opsjonale)
  - [ ] Navn/Lovtittel: title
  - [ ] Beskrivlse: description
  - [ ] Referanser: `rdfs:seeAlso`
  - [ ] Relaterte ressurser: `dct:relation`

Må skille mellom interne lenker og eksterne lenker (hvordan?)

![bilde](https://user-images.githubusercontent.com/108797958/205926695-59e950ea-d970-4db3-9385-83efeac9e211.png)

Depends on
- [x] #1364
- [x] #1362 
- [x] #1363 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/172

**Comment by terjesyl** [comment]
@KurtStian Forstår jeg skissene rett om Regelverk skal vises så lenge det fins data på minst ett av feltene til Regelverket/Ressursen?

**Comment by KurtStian** [comment]
Ja, i utgangspunktet er det tanken. Men det gir kanskje ikke så mye hvis det f.eks. kun er oppgitt språk, utover at man skjønner at den enten har skjedd en feil eller at det finnes en regualtiv ressurs som ikke er beskrevet godt nok.
