### ISSUE TITLE
Bug: understreking av lenker ved linjebrudd

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1405]
# :bug: Bug
Understreking i lenker takler ikke linjebrudd.

## Eksempel
![bilde](https://user-images.githubusercontent.com/108797958/205925981-9846cdf3-00b1-4238-a74c-020cb27e1545.png)
Fra https://data.norge.no/public-services/6ce4e524-3226-3591-ad99-c026705d4259

## Hvor
Feilen er knyttet til [Link-komponenten til fdk-kit](https://github.com/fellesdatakatalog/fdk-kit/tree/develop/packages/link).

## Forslag til løsning
> Begge linjer skal være understreket. Jeg har foreslått at vi dropper border og benytter underline i stedet. Da slipper vi dette problemet =)

**Comment by terjesyl** [comment]
@KjerstiSteien hva kom vi frem til her, var dette intensjonen/som forventet oppførsel? Og skulle vi endre det?

**Comment by KjerstiSteien** [comment]
Jeg synes lenken vil se mer ut som en lenke om teksten er understreket, og det ikke ligger en linje under tekstbolken. Kanskje Mateus og @LeneSundsbo kan se på det og gjøre en vurdering?

**Comment by LeneSundsbo** [comment]
Begge linjer skal være understreket. Jeg har foreslått at vi dropper border og benytter underline i stedet. Da slipper vi dette problemet =)

**Comment by terjesyl** [comment]
Ser nå at denne er fikset av https://github.com/fellesdatakatalog/fdk-kit/pull/154, og at portal bruker ny versjon av @fellesdatakatalog/link. Lukker issuet.
