### ISSUE TITLE
WCAG - Samle-issue for funn etter Tastaturtest

### ISSUE THREAD

**Issue by AinaEngen** [Informasjonsforvaltning/fdk-portal#1417]
Testet i Edge 
Brukt Tabulator for å hoppe fremover, Shift + Tab for å hoppe bakover, samt Enter for å velge

**Søkefelt**
1) Når cursor står i søkefeltet og man trykker tab, blir fokus borte.
Det er X som egentlig har fokus, og da bør dette markeres.
Når man tab'er til Søke-knapp, så får knappen kun en liten blipp i det man kommer til knappen. Her bør det kanskje markeres tydeligere at det er knappen som er i fokus
![image](https://user-images.githubusercontent.com/49443711/207602736-199d5d07-62e0-4115-9146-6358ed58adc7.png)

2) I fra testrapporten fra SVV/Transportportalen, står det også at "Knappen for å fjerne input fra søkefelt (X) har ingen navn". Dette er relevant for tekstopplesningsprogram.

3) Hvordan kan man bla i trefflista som dukker opp når man starter å skrive i søkefeltet? Hvis man trykker Tab, så velges øverste valget i lista. Dvs. brukeren må søke slik at riktig valg blir liggende øverst, hvis ikke får han ikke valgt det.

Gjelder også Søk på Virksomheter (under Om felles datakatalog\virksomheter):

**Snarvei for å hoppe til hovedinnholdet**
Stor skjerm: ok, ser lenke nederst i venstre hjørne med følgende tekst: https://data.norge.no/#content
Mindre skjerm: ser ikke hele lenken, den kutter av siste del av teksten
200% zoom på normal skjermstørrelse (laptop): lenken med snarvei er ikke synlig

**Toppmeny**
1) Hvis man klikker enter på et av valgene i toppmeny, så fortsetter løsningen å tabbe seg gjennom alle toppmenyer m/undermenyer før den går inn i valgt side og fortsetter tab'ing der. 

Eksempel under: Klikker Enter på Veiledning, ser at siden åpnes, men brukeren kommer ikke dit før alle menyene er tab'et gjennom.
![image](https://user-images.githubusercontent.com/49443711/207608608-e43964c7-6049-4324-ae7e-bcda40b3defe.png)

2) Spm: Burde toppmenyene ha lukket seg når man har tab'et seg gjennom dem? Nå er alle åpne når man kommer til hovedinnhold. Se bilde over

**Menyvalg Verktøy - Sparql** 
Hvis brukeren bruker Tab her kommer han inn i Query-bildet, og Tab på linjene gir innrykk i teksten… og man tabber en tab-avstand om gangen i editoren. Da tar det lang tid å tabbe til slutten av bildet og bunnteksten...
![image](https://user-images.githubusercontent.com/49443711/207611183-397cb09c-3734-4084-ab63-3313454e4d6a.png)
Dette burde vel kanskje vært et bilde og heller hatt en link til sparql-kode et annet sted i teksten på denne siden?

**Tab i bunntekst**
![image](https://user-images.githubusercontent.com/49443711/207612003-49a8b63b-c3ed-49f3-95be-7ac6fd6d3807.png)
1) Hvis man tab’er videre etter man har vært innom «Felles datakatalog på Twitter» tas brukeren inn i browser-funksjonalitet.
Tab på siste element burde kanskje tatt bruker til toppen igjen?

2) Når man åpner et av valgene i bunntekst med Enter, og velger Shift + Tab for å gå tilbake. Da ender man på siste tab-elementet i bunnteksten og ikke der man kom ifra. 

**Tab'ing innenfor et publisert datasett**
Har her valgt AREALBRUK 2022 (som vises i bildet)
![image](https://user-images.githubusercontent.com/49443711/207614793-5cdeb258-09c5-41d2-95a0-461c351ad2fd.png)
 1) Trykker Enter på linken «Arealbruk 2022» => jeg tas til en side med mer info om Arealbruk, men ikke til toppen av siden. Lander ca. midt på siden, men valget "Distribusjon" på venstre side i fokus. 
![image](https://user-images.githubusercontent.com/49443711/207615779-fc60fca8-b2f4-4cdf-a120-b0ff4e974945.png)
Burde blitt tatt til toppen av siden

2) Burde vært samsvar mellom aktivt valg på venstre siden og hva som vises på høyre siden

3) I eksemplet fra Arealbruk 2022, så skal det være mulig å åpne panelene som ligger inni Distribusjoner. Dette fungerer ikke. Tab tar ikke bruker inn i disse panelene i det hele tatt. Gjelder alle steder man har slike paneler.
<img width="479" alt="image" src="https://user-images.githubusercontent.com/49443711/207616956-98b5495f-8e6f-43c2-a85b-9c9bbc5af595.png">
Gjelder også i Metadatakvalitet-siden, der det også er en tilsvarende visning:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/49443711/207617851-65cbce30-fba8-48fe-88ad-6e80850a1c1f.png">

**Tab'ing starter i Søkefeltet uansett om katalog er valgt**
Når man først har valgt f.eks. Datasett, og starter å Tabbe, så starter Tab'ing i Søkefeltet igjen og går igjennom alle menyene før man starter Tab'ing i valgte Datasett. Burde ikke Tab startet rett på Datasett siden bruker bevisst har valgt dette ved å trykke Enter.
![image](https://user-images.githubusercontent.com/49443711/207620651-02574117-606c-4666-b9e6-7a8329fcde45.png)

**Filter på venstre side**
1) Hvis man huker av i Tilbyder-filter for eks. Privat, får man ikke mulighet til å åpne meny for flere valg. Åpnes verken med Tab eller Enter. Er det kun mulig å åpne en Tilbyder om gangen? 
![image](https://user-images.githubusercontent.com/49443711/207624111-112c168d-af9d-43ea-8c01-c2d41d4f10a3.png)

2) Format-filter
Testet på API'er
a) Det vises 5 forskjellige formater på skjermen, samt et valg «Vis flere» (som for øvrig har stiplet linje rundt seg når den blir i fokus – burde det vært samsvar mellom kontrastbruk på knapper/linker?). 
Hvis man trykker på «Vis flere», så åpnes liste med flere helt korrekt, men fokus for tab'ing blir stående på «Vis Færre» (nederst), slik at man ikke har mulighet til å fortsette å tabbe nedover i filterlista fra der man var. Brukeren må ta Shift+Tab (tilbake tab'ing) for å tabbe seg gjennom filter-lista. 
Hvis man trykker Tab når man er på slutten av lista, kommer man på toppen av API-beskrivelsene (innholdsdelen). 

b) Når man velger format, markeres dette korrekt i checkbox, men rekkefølgen på formatene endrer seg på skjermen, men rammen som viser fokus blir stående på samme sted i lista. Se under, hvor en er huket av, mens en annen har fokus-ramme rundt seg.
![image](https://user-images.githubusercontent.com/49443711/207624772-cdda46ac-5309-4b55-9685-e755f8114ec0.png)
Dette gjelder for øvrig overalt i filtrering.

3) Menyene på venstre side åpnes ikke ved bruk av tastatur-navigering
![image](https://user-images.githubusercontent.com/49443711/207633607-3265c30c-76fe-49d8-8b62-b527a4febe10.png)

**Eier-link - Datasett**
kommer hit: 
![image](https://user-images.githubusercontent.com/49443711/207627816-4323b1be-f19f-40be-83eb-3ada354173d4.png)

Klikk på et av valgene under «datasettbeskrivelser»
![image](https://user-images.githubusercontent.com/49443711/207628103-949f863d-7c83-48ab-9046-9fe0467ce30c.png)
Kommer til fanen Datasett, filtrert på eier-valget. Hvis man trykker Shift + Tab for å komme tilbake dit man var, så fungerer ikke det. Man kommer da til «Language» i toppmeny… (ikke logisk).(Hvis jeg tar Back i browser, så kommer jeg tilbake til Eier-siden der jeg kom fra).
Dette gjelder alle valg på denne siden

**Nullstille filter på labels**
Går inn i en Datasettbeskrivelse, og tabber frem til labels/filter. Klikker Enter på en gitt label.
Trykker Shift + Tab for å kunne nullstille filter/endre filter. Ta starter tilbake-tab'ing fra bunnen av filterlista og man må tabbe helt til toppen. Det er tungvindt.  Burde det startet på toppen, der man har filteret? 

**Mangler tekst på bilde ved Tab'ing**
Datasetttbeskrivelser. Her ligger det et bilde (som ser ut som en knapp) - «Åpne data med åpen lås». Denne har mouseover-tekst, men denne teksten er ikke synlig når man kun bruker tastatur da bruker ikke kommer innom denne knappen ved bruk av Tab. 
Alle bilder skal ha beskrivende tekst.
![image](https://user-images.githubusercontent.com/49443711/207630333-695a57d3-e89b-4d7c-ae07-1d276fea2f90.png)

Stjernen etter navnet, har også mouseover tekst. Denne er utilgjengelig for Tastatur-brukere, da Tab ikke er innom stjernen

Bilde på Metadatakvalitet-siden
Hvis man klikker på link "Lær mer om metadatakvalitet», ligger det et bilde med beskrivelse av hva metadatakvaliteten betyr. Dette vil ikke en tastatur-bruker eller svaksynt kunne se. Bildet må ha en forklaring som nås av alle. Burde man ikke bare skrive inn dette i tekstform i stedet for et bilde?
Oppfyller ikke krav 1.4.5 (må krav)	

**Mouseover-tekst vises ikke ved tab'ing (eller leses opp ved opplesning).**
![image](https://user-images.githubusercontent.com/49443711/208443589-f0562e81-a899-44db-8157-4b42c847d566.png)

**Comment by jeffreiffers** [comment]
Søkefelt 3: Trenger bedre forklaring

**Comment by jeffreiffers** [comment]
Bug meny detaljsiden løses her: https://github.com/Informasjonsforvaltning/fdk-portal/issues/1442
