### ISSUE TITLE
WCAG - forstørrelse av tekst

### ISSUE THREAD

**Issue by AinaEngen** [Informasjonsforvaltning/fdk-portal#1419]
WCAG-Krav: Skal kunne forstørre tekst opp til 200% og 400% uten av innhold blir borte

Testet i Edge

Forstørrelse 150%
Første siden ser bra ut, Valgene (datasett, api, begrep osv) vises under hverandre.
![image](https://user-images.githubusercontent.com/49443711/207635163-4ef4e3af-64ad-44f1-9bbf-92eb02b1521b.png)

For å vise toppmenyen (Datafabrikken, Publisering, språk etc), må man trykke på Meny. Da kommer menyene under hverandre, men enkelte valg mangler. Det er heller ikke mulig å scrolle med pil eller mus nedover, og det er heller ingen scrollbar på høyreside.
(menyvalget «Verktøy» mangler, samt at det kun er synlig Norsk (bokmål) som språk (skulle hatt nynorsk og engelsk også). 
![image](https://user-images.githubusercontent.com/49443711/207635288-30f7e388-aa53-4da3-b033-b8a3abc8e5ee.png)

Hvis man øker til 175% eller 200% (eller enda høyere) er det enda mindre som vises av menyen.

400%: Ved Tab fra Overskrift, forsvinner scrollbar på side og nederst, og får ikke navigert på siden med Tab. Hvis jeg klikker på skjerm med mus kan jeg bevege meg nedover skjermen, men scrollbarene er fortsatt borte

![Image](https://user-images.githubusercontent.com/49443711/208666633-f7827b40-adb6-4b5f-ab91-5b259fab0ddb.png)

**forklaring til ikon/bilder mangler - alle bilder/ikoner skal ha tekstforklaring**
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/49443711/208445772-136998b5-f6d8-4d50-89f7-6b9238d1271b.png">

**Comment by jeffreiffers** [comment]
Klarer ikke gjenskape problemet rundt 400% og scrollbar som forsvinner.
