### ISSUE TITLE
[Tjeneste] komponenten 'Tema og Søkeord'

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-portal#1427]
- [x] Legg til informasjon om søkeord (`keyword` i JSON-respons)
- [x] Erstatt "nøkkelord"-label med "søkeord".

~~`thematicAreas` : uri-er til tema~~
~~`euDataThemes` : objekter med EU-temaer~~
~~`losThemes` : objekter med våre egne temaer~~

~~Feltet name fra LosTema skal vises og title fra EuDataThemes.
"Tema" = LosTema, "EU-tema" = EuDataTema~~

![image](https://user-images.githubusercontent.com/48259307/208457117-0efc74de-0c8e-487c-8599-fa6200473ae4.png)

**Comment by hegeaal** [comment]
@KurtStian URI-er som ikke er i kodelistene til EU eller LOS, skal de fortsatt vises?

**Comment by KurtStian** [comment]
@hegeaal Hvilke URI-er er dette?

**Comment by terjesyl** [comment]
Ble enig om å ignorere URI-ene i thematicAreas, viser kun det som er i LosThemes og i EuDataThemes.

**Comment by terjesyl** [comment]
@hegeaal Venter på en avklaring om spec'en i forhold til Tema. Keyword/Søkeord kan vises i frontend, ThematicArea (thematicAreaUris, LosThemes og EuDataThemes) kan ignoreres i denne omgang.

**Comment by terjesyl** [comment]
@KurtStian Gi oss en lyd når dere vet hva som skal gjøres med temaer, så ordner vi issue på det.
