### ISSUE TITLE
BUG: Tjenester i tjeneste og hendelse katalog mangler kompetent organ

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-portal#1479]
### Nåværende oppførsel
Viser ikke kompetent organ
![image](https://user-images.githubusercontent.com/48259307/212015575-f7f63c16-7c3d-4e3a-9cfa-4327cb70da03.png)

![image](https://user-images.githubusercontent.com/48259307/212015523-34746578-87b0-4375-a734-4f4fed46bbc7.png)

### Forventet oppførsel
![Screenshot 2023-01-12 at 09 28 38](https://user-images.githubusercontent.com/48259307/212016442-580d6efe-0241-49a9-8983-cc051e7ebbbd.png)
![Screenshot 2023-01-12 at 09 29 08](https://user-images.githubusercontent.com/48259307/212016473-873ee752-a77c-477e-b5ee-a0b2b8e8a9a3.png)

Burde vise kompetent organ både i listevisningen og i detaljvisningen

### Hvordan reprodusere?
https://staging.fellesdatakatalog.digdir.no/public-services-and-events 
https://staging.fellesdatakatalog.digdir.no/public-services/31249174-df02-3746-9d61-59fc61b4c5f9

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by terjesyl** [comment]
@hegeaal Ble denne fikset?

**Comment by hegeaal** [comment]
@terjesyl Wops, ja det skal være fikset!
