### ISSUE TITLE
BUG: tomme headere

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-portal#1498]
## 🐛 Bug rapport
Fjern tomme header som kommer inn med Strapi/Drupal.

### Eksempel
![image](https://user-images.githubusercontent.com/50879748/212921782-1340be48-3d96-4130-be20-28e7e7a56070.png)

### Forslag/Løsning [Valgfritt]
Sjekk dette issuet for mer info: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/667

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by pooriamehregan** [comment]
Mistenker at dette er en duplikat av

**Comment by KjerstiSteien** [comment]
Lukket. Duplikat av #667
