### ISSUE TITLE
BUG: Transportportal - Språkvelger med for små interaktive elementer

### ISSUE THREAD

**Issue by AinaEngen** [Informasjonsforvaltning/fdk-portal#1532]
## 🐛 Bug rapport
Mottatt fra Vegvesenet, etter wcag-test av Transportportal:

Språkvelger med for små interaktive elementer – Interne retningslinjer

Det finnes interne retningslinjer hos SVV om at interaktive elementer minst skal være 24*24px
store. Dette er for at det skal være enkelt for alle å treffe de interaktive elementene. Målt størrelse
på falgg/språkvelger på transportportal.atlas.vegvesen.no er særdeles små, 16*21,33px. Gjør
disse til minst 24x24px. 

<img width="176" alt="image" src="https://user-images.githubusercontent.com/49443711/217002737-f1bff558-069f-4822-a2cf-5f4922819e84.png">

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by terjesyl** [comment]
Klar til å tas tak i
