### ISSUE TITLE
BUG: Transportportal - dokumenter innfrir ikke krav til UU

### ISSUE THREAD

**Issue by AinaEngen** [Informasjonsforvaltning/fdk-portal#1533]
## 🐛 Bug rapport
Fra regresjonstest av Transportportal, gjennomført av Vegvesenet

Dokument – 1.3.1
Dokumenter skal som nettsider innfri kravene til universell utforming av IKT. Dokumentet
«MallDatasett.pdf» er et eksempel på et dokument som ikke innfrir disse kravene. Til eksempel
er ikke skriften på toppen av dokumentet definert som skrift, men bilde av skrift. Første overskrift
er en h2. Footer innholdet blir presentert før hovedinnholdet på siden. Det benyttes også tomme
paragrafer for å skap mellomrom mellom innhold, noe som ikke er ideelt.
MalDatasett.pdf (vegvesen.no)

<img width="491" alt="image" src="https://user-images.githubusercontent.com/49443711/217006935-1c5f5614-d75f-422e-9f8d-dca8ebca2dcf.png">

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by jeffreiffers** [comment]
Dokumentene er laget av Vegvesen.

**Comment by KjerstiSteien** [comment]
Vi løser ikke dette, da dette er vegvesenet sitt ansvar å løse.
