### ISSUE TITLE
BUG: Transportportal - Ugyldig bruk av aria/HTML

### ISSUE THREAD

**Issue by AinaEngen** [Informasjonsforvaltning/fdk-portal#1535]
## 🐛 Bug rapport
Funn etter reg.test gjennomført av Vegvesenet på Transportportal

Ugyldig bruk av aria/HTML – 4.1.1
Pageination elementene er wrappet i ul med role navigation. Dette overskriver semantikken ti ul
elementet. Således er det løse < li > elementer som ikke er wrappet i ul eller ol. Dette bryter med
HTML standarden og et direkte brudd på 4.1.1.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/49443711/217012236-8d62c277-b4b9-4437-be55-a59f9b95ca54.png">

Dette gjelder på samtlige steder hvor pagination er benyttet

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

### Løses gjennom:
- [ ] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1819

**Comment by KjerstiSteien** [comment]
@jeffreiffers tar dere en diskusjon på hvilket alternativ vi burde velge her?

**Comment by hegeaal** [comment]
Vurder å bytte til aksel.nav sin paginering? Undersøk om det ville vært mulig å legge den inn i digdir felles designsystem slik at man slipper å forholde seg til flere designsystem.

**Comment by KjerstiSteien** [comment]
Skal vi vurdere å bytte til designsystemet sin pagination nå? @hegeaal @jeffreiffers ?

**Comment by hegeaal** [comment]
> Skal vi vurdere å bytte til designsystemet sin pagination nå? @hegeaal @jeffreiffers ?

Tror vi kan det! Virker som at den fungerer fint @pooriamehregan ?

**Comment by pooriamehregan** [comment]
> > Skal vi vurdere å bytte til designsystemet sin pagination nå? @hegeaal @jeffreiffers ?
> 
> Tror vi kan det! Virker som at den fungerer fint @pooriamehregan ?

Ja fungerer bra!
