### ISSUE TITLE
WCAG: ta i bruk ny verjson av ikon-pakke

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1600]
Ta i bruk ny versjon av ikon-pakke fra fdk-kit, hvor id="stroke" har blitt fjernet fra alle svg-ene.

Pakke: `@fellesdatakatalog/icons 0.8.4`

Gjør at vi unngår id-kollisjoner i HTML-dokumentet.
Forbedrer score på tilgjengelighetsvurderinger (SiteImprove, Pa11y ++)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Knyttet til https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/672

**Comment by KjerstiSteien** [comment]
@terjesyl @Lillebo skal vi lukke denne og heller bruke tid på å gradvis gå over til designsystemet?
