### ISSUE TITLE
BUG: kilde vises ikke riktig på søkesiden

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1601]
### Nåværende oppførsel
Kilde vises ikke riktig i treff på søkesiden:
![image](https://user-images.githubusercontent.com/108797958/226898916-25646d0f-f89c-45f9-b8ae-a2e1cbd74f6f.png)

### Forventet oppførsel
Forventer at riktig tekst vises, objekt  med tekster er tilgjengelig i JSON-respons.

### Hvordan reprodusere?
Gå inn på https://data.norge.no/concepts, søk med ctrl+f etter "object"

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Løst av https://github.com/Informasjonsforvaltning/fdk-portal/issues/1731
