### ISSUE TITLE
BUG: Alle språk vises på søkeord uansett valgt språk

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-portal#1615]
### Nåværende oppførsel
Alle språk vises på søkeord uansett valgt språk

### Forventet oppførsel
Kun søkeord som matcher valgt språk i portalen skal vises.

### Hvordan reprodusere?
Se: https://staging.fellesdatakatalog.digdir.no/public-services/309d00a5-1887-314b-a609-a639905c3ab9

![image](https://user-images.githubusercontent.com/43232700/231394256-ba5b6820-ad73-4fc2-82d2-0c6fa1c192b8.png)

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by terjesyl** [comment]
Undersøk i parser

**Comment by terjesyl** [comment]
Responsen fra backend ser ut til å være riktig, kan du sjekke koden i frontend @hegeaal ?
![bilde](https://user-images.githubusercontent.com/108797958/231988376-b8356f80-9338-4df6-8497-405f5ab0f54d.png)

**Comment by terjesyl** [comment]
Foreslår vi filtrerer på keyword i frontend. Alternativt kan vi endre parseren slik at alle engelske ord legges i en liste, alle bokmålsord i en osv. `keywords: [ en: ["wordA", "wordB"], nb: ["ordA", "ordC"], ...]` men tror det også krever endringer i frontend så det kan bli merarbeid.

**Comment by KurtStian** [comment]
@terjesyl Har du sjekket hvordan dette er løst for datasett?

**Comment by terjesyl** [comment]
I backend gjøres det på samme måte for tjeneste og datasett, så en endring i backend vil kreve endringer i frontend for datasett, datatjenester og tjenester.

**Comment by terjesyl** [comment]
I frontend kan visning av søkeord på tjenester trolig gjøres likt som for datasett, @hegeaal undersøker.
