### ISSUE TITLE
BUG: Hovedformål (dct:type) vises ikke for offentlig tjeneste

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-portal#1621]
### Nåværende oppførsel

Hovedformål (dct:type) vises ikke for offentlig tjeneste.

![image](https://user-images.githubusercontent.com/43232700/231480740-113e5fbd-1ca5-4e2a-8ab7-0b13d69f2add.png)
Fra opprinngelige desingskisse: 
![image](https://user-images.githubusercontent.com/43232700/231481942-d3651e83-9aeb-478f-8150-1701c27f2387.png)

### Forventet oppførsel

Hovedformål vises tilsvarende designskissen, men flyttes foreløpig fra den ekstra høyrekolonnen inn til den midtre kolonnen.

### Hvordan reprodusere?

Se tjeneste: https://staging.fellesdatakatalog.digdir.no/public-services/309d00a5-1887-314b-a609-a639905c3ab9

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by terjesyl** [comment]
Trenger design på visning.

**Comment by pooriamehregan** [comment]
@matfuru Da venter jeg på din signal :)

**Comment by KurtStian** [comment]
Lenke til spesifikasjonen angående Hovedmål for Offentlig tjeneste: https://informasjonsforvaltning.github.io/cpsv-ap-no/#OffentligTjeneste-hovedform%C3%A5l
For tjenester som ikke er offentlig: https://informasjonsforvaltning.github.io/cpsv-ap-no/#Tjeneste-type

**Comment by matfuru** [comment]
Hovedformål (offentlig) er flyttet i egen card under beskrivelse: https://www.figma.com/file/N5yRmXN2WW6sv6J3ILiav7/Portal-%E2%80%93-Detail?type=design&node-id=6584%3A63431&mode=design&t=jpTUT4Fwh7zKd6rV-1

Type tjeneste (ikke offentlig) er flyttet i egen card under beskrivelse: https://www.figma.com/file/N5yRmXN2WW6sv6J3ILiav7/Portal-%E2%80%93-Detail?type=design&node-id=6584%3A97001&mode=design&t=jpTUT4Fwh7zKd6rV-1

**Comment by KurtStian** [comment]
Eksempel på staging der hovedformål ikke vises for offentlig tjeneste: https://staging.fellesdatakatalog.digdir.no/public-services/42e14526-d0b6-3faf-a891-6254b66c0825

**Comment by terjesyl** [comment]
Så vidt jeg kan se er kodene som brukes for hovedformål/type begrenset til dem fra EU sitt Main Activity-vokabular, andre custom ord som ansvarlige for beskrivelsen legger til ignorereres. Er en begrensning i fdk-rdf-parser, som krever en større endring enn kun denne fiksen. Vokabularet inneholder heller ikke norske oversettelser, som betyr at koden alltid vil vises på engelsk.
