### ISSUE TITLE
WCAG: Skip-lenke fungerer ikke, transportportal

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-portal#1627]
**Skip-lenke fungerer ikke 2.4.1 – Ikke godkjent**
På data.transportportal.no er nå skip-lenken funksjonell, men presenteres kun for seende
brukere. Også seende tastaturbrukere har behov for skip-lenken. Skip-lenken skal altså bli synlig
når den får fokus. Vi liker veldig godt skip-lenken på valg.no dersom dere har behov for
inspirasjon (ps: kontrasten på teksten i skip-lenken til valg.no er ikke tilstrekkelig).

**Comment by KjerstiSteien** [comment]
Får synlig "skip to content"-lenke på alle sider jeg har testet på transportportal.no. Regner denne som løst.
