### ISSUE TITLE
Brutt lenke til veileder om åpne data

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1638]
### Nåværende oppførsel
Lenke til "Veileder for tilgjengeliggjøring av åpne data" på https://data.norge.no/publishing leder til en gammel difi-side (https://doc.difi.no/data/veileder-apne-data) som gir 404. 

![bilde](https://user-images.githubusercontent.com/108797958/233973215-3021a02a-b8d2-49c1-8c8e-ccad1ee57a7d.png)

### Forventet oppførsel
Lenken peker til faktisk veileder: https://data.norge.no/guide/veileder-apne-data

Kjersti ønsker at https://github.com/Informasjonsforvaltning/fdk-portal/issues/1464 løses samtidig som denne.

Løs 
### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by terjesyl** [comment]
Kan du poste lenke til den faktiske veilederen, @KjerstiSteien ?

**Comment by KurtStian** [comment]
@terjesyl  Lenke til veileder: https://data.norge.no/guide/veileder-apne-data
