### ISSUE TITLE
Feltet dctType for datasett må støtte objekt med språkdata

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-portal#1664]
Feltet er nå bare type string, men skal utvides til et objekt som inneholder språkdifferansiert prefLabel

Blokkert av: https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/249

**Comment by KurtStian** [comment]
Det er bare et utdrag av de 23 kodene som skal være tilgjengelig i reg.løsningen.
