### ISSUE TITLE
BUG: "Skip to content" på virksomhetssiden leder til søkesiden på data.norge.no og ikke til hovedinnold

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1677]
### Nåværende oppførsel
Når man tabber seg til "Skip to content" og trykker enter tas man til søkesiden på data.norge.no, (https://data.norge.no/#content)
![bilde](https://github.com/Informasjonsforvaltning/fdk-portal/assets/108797958/3ccbf7dc-981c-4212-917a-761af520275a)

### Forventet oppførsel
Forventer at markør tas til hovedinnhold på virksomhetssiden.

### Hvordan reprodusere?
- Gå inn på https://data.norge.no/organizations
- Trykk på Tab-knappen én slik at "Skip to content" vises og er markert
  - Forutsetter at ikke et annet element er markert/aktiv når man går inn på siden, noe som er tilfellet når man klikker seg inn på virksomhetssiden fra data.norge.no
- Trykk på Enter

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by terjesyl** [comment]
Ser ut som at en annen feil er introdusert nå: det er ikke mulig å tab-e seg til Skip to Content-knappen.

**Comment by KjerstiSteien** [comment]
Se på hvordan dette fungerer helhetlig
