### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-portal#1684]
## 🐛 Dependency update

Ta med foreslåtte oppdateringer fra dependabot.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Vi må følge opp depandencies på andre måter. Lukker denne.
