### ISSUE TITLE
featuretest for fdk-portal

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#17]
Ta utgangspunkt i
a-frontend-service
a-backend-service

og verifiser at de ulike tjenestene har en specc fil.
Deretter skal vi skrive kontrakttester/featuretester for den enkelte tjenesten.

Implementere kontrakttest/featurestest for tjenesten:
fdk-portal

**Comment by azaxarov** [comment]
Won't fix
