### ISSUE TITLE
BUG:  Kilder vises ikke som link

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-portal#1734]
## 🐛 Bug rapport

I trefflista for begrep viste i utgangspunktet en kilde som [object Object], men gjorde en quick fix og endret til å vise bare name (vanlig string). Burde vises slik som på det nederste bildet isteden. Problemet virker å være at man ikke får lov til å rendre en komponent (lenke) da man får man react `Minified React error #31`. Det er kun string man får lov til å rendre, som gjør at man ikke får vist den klikkbare lenken. 

![Screenshot from 2023-07-07 08-48-20](https://github.com/Informasjonsforvaltning/fdk-portal/assets/50194012/96f37933-2319-4ef6-9b07-26514b993d34)

Samme kilde vises korrekt på detaljsiden:

![Screenshot from 2023-07-07 08-49-00](https://github.com/Informasjonsforvaltning/fdk-portal/assets/50194012/0f8d17ba-9c21-4032-8f13-579b1039b24c)

Det forrige issuet: https://github.com/Informasjonsforvaltning/fdk-portal/issues/1731

**Comment by KjerstiSteien** [comment]
https://github.com/Informasjonsforvaltning/fdk-portal/issues/1731
