### ISSUE TITLE
Endre email + lenke til personvern i footer

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#181]
- [ ] ![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/6a3c614d-1593-49a6-8285-43952d77bc44)
skal være fellesdatakatalog@digdir.no 

- [ ] Lennke personvern skal hit: https://www.digdir.no/om-oss/personvernerklaering/706

**Comment by joebrreg** [comment]
@lillelars Hva er status her?

**Comment by lillelars** [comment]
Denne ser ut til å være fikset på samtlige sider, lukker derfor denne.
Testet i staging, demo og prod.

**Comment by lillelars** [comment]
Her har det skjedd en beklagelig feil....
Epost skal være:
fellesdatakatalog@digdir.no !!

**Comment by lillelars** [comment]
Er nå rettet over alt i registreringsløsningen også. Lukker denne.
