### ISSUE TITLE
BUG: paginering fungerer ikke riktig for oversikt over etterspørsler 

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-portal#1815]
### Nåværende oppførsel
Pagineringen oppfører seg rart på oversikt over etterspørsler. 
Antall på hver side endrer seg etter hvert som jeg blar, det samme gjør hvilke treff jeg ser. 

### Forventet oppførsel
Jeg forventer at hver side viser like mange treff, så lenge det finnes nok treff til å fylle siden. Jeg forventer å se de samme treffene på samme side hver gang jeg blar til siden. 

### Forslag/Løsning [Valgfritt]
a) Fikse paginering til å bli mer stabilt
b) Fjerne paginering

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by hegeaal** [comment]
Har fått ok fra Livar om at vi kan fjerne "antall visninger" og "Vis alle"-knappen. Dette vil fikse pagineringsproblematikken.
