### ISSUE TITLE
Feature: bytte til designsystemets pagination på transportportal.no

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-portal#1819]
### Feature beskrivelse
Vi ønsker å gå over til designsystemets løsning for pagination på transportportal.no

### Hvorfor trenger vi det?
For å løse wcag-feil og for å ha lik løsning for pagination i alle løsningene vi forvalter.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
@pooriamehregan ble du ferdig med dette?

**Comment by pooriamehregan** [comment]
Nei, har ikke fått nok tid til å gå videre med det. Skal se på det nå :)

**Comment by pooriamehregan** [comment]
Jeg har nå laget en pr på det 👆. 
FDK-Portal og Transport-portal delte samme Pagination-komponent, derfor bruker nå begge Pagination-komponenten fra designsystemet.
