### ISSUE TITLE
sende søketrafikk til ny søketjeneste

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-portal#1894]
- [x] Opprett ny feature-branch som har workflow for deploy til staging
- [x] Opprett ny miljøvariabel som går til `search.api.*.fellesdatakatalog.digdir.no`
- [ ] #1908

Miljøvariabler i fdk-portal som potensielt sender trafikk til fulltext:
- SEARCH_API_HOST
- SEARCH_HOST
- SEARCH_FULLTEXT_HOST

**Comment by KjerstiSteien** [comment]
Vi har ikke fullstendig oversikt her. Den som plukker saken må sjekke at listen i saken er komplett.

**Comment by NilsOveTen** [comment]
> Vi har ikke fullstendig oversikt her. Den som plukker saken må sjekke at listen i saken er komplett.

Tenker vi kan si at denne er ok når vi ser at vanlige søk i staging blir sendt til nye søketjenesten, om vi senere ser at noe fortsatt går til fulltext så kan vi opprette bug-issues
