### ISSUE TITLE
Begreper detaljside: Begreper relatert tittel vises uten relaterte begreper

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#19]
Testet i chrome, i demo:

Gjenskape feilen:
- Åpne Begrepet "Reisefeber" (eller et annet begrep uten relasjoner) - da ser du at begrepet ikke har noen relasjoner
- gå tilbake til oversikten og åpne begrepet "test utgått begrep" (eller et annet begrep med relasjoner)
- Gå så tilbake til "Reisefeber". Da ser du at overskriften relasjoner vil være der uten noen relasjoner.
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/288bbdaf-4067-4560-ab07-c0136c9f1752)

**Comment by azaxarov** [comment]
@lillelars Kan denne lukkes nå? Vi har jo reimplementert detaljsiden vår.

**Comment by lillelars** [comment]
Etter nytt design er ikke dette feil lenger. Lukker derfor denne.
