### ISSUE TITLE
Søkefeltet ser stygg ut i firefox og Safari

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#191]
- [ ] I Firefox (knapp må fikseS): ![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/9a85e867-7fa8-4ede-9e57-d78623433dfb)

- [ ] I Safari (hele feltet eskalerer?)

![image](https://user-images.githubusercontent.com/39513382/77731634-8cf06900-7003-11ea-8263-a56d9979911d.png)

**Comment by lillelars** [comment]
@oyvindis Denne er i prod, så må fikses

**Comment by eggedosis** [comment]
![Screenshot 2020-03-31 08 11 45](https://user-images.githubusercontent.com/25385497/77992901-524e3f80-7327-11ea-8cda-dad1503644f0.png)

Småpirk fra meg:

1. Fremdeles blir det veldig bredt på stor skjerm både i safari og chrome (se bilde). Bredden bør maks være 1110 px (samme som innholdet på siden).

2. Knappen skal være neutral-darker, og neutral-darkest kun hover.

3. Hadde også vært fint med litt mer luft mellom X og Søk-knapp =)

**Comment by lillelars** [comment]
@eggedosis kan du teste om dette fungere rsom forventet nå?

**Comment by eggedosis** [comment]
@lillelars  I staging i Safari kan jeg ikke se noen endringer.

**Comment by lillelars** [comment]
Testet på ny i sfari. Fungerer nå
