### ISSUE TITLE
"Something went wrong" er tilbake på rapportsiden

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#192]
Reproduser:
1) Benyttet Chrome i stagingmiljøet.
2) gå til rapportsiden
3) Søk opp og Velg virksomhet fra menyen til venstre
4) resultatet er "something went wrong":

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/c60b739c-e161-4b88-b9ff-8a2a26200b96)

**Comment by azaxarov** [comment]
@azaxarov Dette har med output fra concept-harvester å gjøre.

Dette kallet vil ikke forårsake feil i portal: https://www.staging.fellesdatakatalog.digdir.no/api/concepts?orgPath=%2FSTAT%2F972417866&size=1&returnfields=uri&aggregations=firstHarvested,publisher

Denne gjør at portal ikke funker: https://www.staging.fellesdatakatalog.digdir.no/api/concepts?orgPath=%2FSTAT%2F983887457&size=1&returnfields=uri&aggregations=firstHarvested,publisher

Forskjellen er output fra APIet. I det ene caset så finnes "_embedded.concepts", mens det gjør ikke i det andre. Du kan høre med @rannveigskjerve hvordan det er tenkt skal funke
