### ISSUE TITLE
Feature: Legg til transportportal i filterbody

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-portal#1939]
## 🚀 Feature forespørsel

Relatert til denne: https://github.com/Informasjonsforvaltning/fdk-search-service/pull/135

Legg til støtte for eget filter når man er i transportportalen , utklipp av den gamle koden 👇

```
 // Filter out NAP data if filterTransportDatasets in conf is true
  if (getConfig().filterTransportDatasets) {
    filters.push(
      { accessRights: 'PUBLIC' },
      {
        themeprofile: 'transport'
      }
    );
  }
```

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
Backend ble klargjort her: https://github.com/Informasjonsforvaltning/fdk-search-service/commit/848e7a4f866fa33f9dbef4de90a48c6c0d4aef0f

`themeprofile` fjernes fra `filters`, navnet endres til `profile` og ligger ved siden av `filters`. I tillegg endres verdien `transport` til `TRANSPORT`
