### ISSUE TITLE
Flytte datajegeren

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-portal#1980]
## Brukerhistorie
Som datajeger ønsker jeg at brukere skal kunne etterlyse data på en strukturert måte, med informasjonen jeg trenger, slik at jeg slipper å bruke unødvendig mye tid på å be om mer informasjon. 

Design: https://www.figma.com/proto/pRJQLuOi6JGjIigt1h2JY4/data.norge.no?page-id=0%3A1&type=design&node-id=482-12463&viewport=-3695%2C-3375%2C0.43&t=YoEPHLPeHyG0hx6Q-1&scaling=scale-down-width&starting-point-node-id=71%3A3747

## Innhold på siden: 
**Overskrift:** 
Datajegeren hjelper deg å finne data

**Ingress:** 
Finner du ikke datasettet du trenger? Mange datasett fra offentlig sektor er tilgjengelige via vår datakatalog, men denne er ikke komplett. Datajegeren hjelper bedrifter med å finne og få tilgang til datasett fra offentlig sektor.

**Skjema:** 
| Feltnavn | Forklarende tekst | Type felt | Obligatorisk |
| --- | --- | --- | --- |
| Hvilket datasett trenger du? | Lag en så tydelig beskrivelse som mulig, f.eks. felter, tidsperiode, ønsket oppdateringsfrekvens. | Textarea | Ja |
| Vet du hvor datasettet befinner seg? | Hvis du har informasjon om hvor du tror vi kan finne datasettet, f.eks. hos hvilken offentlig etat eller kommune, kan dette være til stor hjelp for datajegeren. | Textarea | |
| Har du forsøkt å få tak i dette datasettet selv? | Hvis du har gjort forsøk på å få tak i datasettet selv, oppgi hvor du har søkt og ev. hvem du har snakket med. Ta gjerne med hvorfor du ikke lykkes hvis du har vært i direkte kontakt med noen i offentlig sektor. | Textarea | |
| Organisasjonsnummer | | Textfield | Ja | 
| Ditt navn | | Textfield | Ja |
| E-postadresse | | Textfield | Ja | 
| Telefonnummer | | Textfield | | 

## Retningslinjer:
Siden skal skrives i next.js
Komponenter hentes fra designsystemet
Siden skal følge akseptansekriteriene. 
Det skal skrives automatiserte tester ut fra akseptansekriteriene. 
Løsningen skal wcag-testes før produksjon
Vurder om noe må gjøres i GCP for at tjenesten skal fungere.
Gjennomfør en trusselmodellering 

## Akseptansekriterier: 
- [x] Det finnes en side for datajegeren
- [x] Siden for datajegeren inneholder overskrift, tekst og et skjema som kan fylles ut av bruker. 
- [x] Skjemaet inneholder feltene beskrevet i tabellen over
- [x] Feltene i skjemaet har riktig felttype. Se tabellen over.
- [x] Obligatoriske felt skal være merket som obligatoriske. Se tabellen over for hvilke felt dette gjelder. 
- [x] Bruker skal enkelt kunne oppdage at et obligatorisk felt ikke er fylt ut. 
- [x] Det er ikke mulig å sende inn en forspørsel når obligatoriske felt ikke er fylt ut.
- [x] Felt for e-post har valideringsregel for format på innhold i feltet. (x@x.xx)
- [x] Det er mulig for bruker å sende inn forespørsel. 
- [x] Sending av forespørsel generer en epost til datajegeren@digdir.no
- [x] All informasjon som skrives inn i skjemaet blir med i eposten. 
- [x] Bruker får en kvittering på at forepørselen er sendt inn
- [x] Det finnes et menypunkt for datajegeren under verktøy i toppmenyen som viser til siden.

Avklaringer: 
* Skal dette være den første siden i et monorepo? Sjekke med Roberto om det er mulig å inkludere Eirik i denne avgjørelsen.

**Comment by pooriamehregan** [comment]
https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/916

**Comment by Lillebo** [comment]
### Akseptansetest status:

- ✅ Det finnes en side for datajegeren
- ✅ Siden for datajegeren inneholder overskrift, tekst og et skjema som kan fylles ut av bruker.
- ✅ Skjemaet inneholder feltene beskrevet i tabellen over
- ✅ Feltene i skjemaet har riktig felttype. Se tabellen over.
- ✅ Obligatoriske felt skal være merket som obligatoriske. Se tabellen over for hvilke felt dette gjelder. 
- ✅ Bruker skal enkelt kunne oppdage at et obligatorisk felt ikke er fylt ut. 
- ✅ Det er ikke mulig å sende inn en forspørsel når obligatoriske felt ikke er fylt ut.
- ✅ Felt for e-post har valideringsregel for format på innhold i feltet. (x@x.xx)
- ❌ Det er mulig for bruker å sende inn forespørsel. 

Innsending gir `403 Forbidden` med følgende data:
		
	Hvilket datasett trenger du: Test
	Navn: Test Testesen
	E-post: test@test.test
	Organisasjonsnummer: 991825827



![Image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/74510/4e6f6e10-d952-481f-b338-4ed7f1f0fc59)

- ❔ Sending av forespørsel generer en epost til datajegeren@digdir.no
- ❔ All informasjon som skrives inn i skjemaet blir med i eposten.
- ❔ Bruker får en kvittering på at forepørselen er sendt inn
- ✅ Det finnes et menypunkt for datajegeren under verktøy i toppmenyen som viser til siden.

**Comment by Lillebo** [comment]
Feil under innsending burde kanskje også kommuniseres til brukeren på et vis? En feilmelding burde kanskje vises under/over submit-knappen som sier noe ala "En feil oppstod, prøv igjen senere" eller noe sånt?

**Comment by livarb** [comment]
Noko GCP-filter som blokkerte innsendinga kanskje?
Testa nettopp skjemaet og det fungerte.

Kva er feilmeldingsteksten som vert vist til brukar? Tidlegare hadde vi med i formulering i feilmeldinga om at ein kunne ta kontakt på datajegeren@norge.no, nettopp for at brukarane hadde eit alternativ ved problem. Få gjerne med e-postadressa dersom den ikkje er med i dagens feilmeldingstekst.

**Comment by Lillebo** [comment]
Ja, jeg tror @valosnah fikset det ganske kjapt 🙂 Nå funker innsending hos meg også 👍 

Per nå ser det ikke ut som at det blir vist noe feilmelding til bruker hvis innsending feiler. Synes det er en god idé å fortelle brukeren at hen kan ta kontakt med datajegeren som et alternativ.

Kanskje noe ala:

>En feil oppstod, vennligst prøv igjen senere. Hvis problemet vedvarer kan du få hjelp ved å kontakte datajegeren@norge.no

**Comment by Lillebo** [comment]
Kan jeg foreslå at success-notisen flyttes fra øverst i skjemaet til under submit-knappen? Slik det er nå så er det litt vanskelig for brukeren å oppdage at det kommer en grønn notis på toppen av siden når man trykker på submit:

![Image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/74510/4cc66d9e-6128-4201-84f7-ab2884d72f54)

![Image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/74510/3c7f24ec-9ce7-4c47-8423-faaba3fa2559)

**Comment by pooriamehregan** [comment]
Feilhåndtering og visning av feilmelding Skulle egentlig håndteres av appen. Har nå testet med `403 Forbidden` som du fikk under test, men klarte ikke å reprodusere at feilmelding ikke vises. Det vises en rød alert ved feil. Hvis du kommer over denne feilen igjen si gjerne i fra om hvordan jeg kan reprodusere den. 

Og alerten er nå flyttet under submit-knappen. Godt forslag! 👍

![Screenshot 2024-06-14 at 17 01 28](https://github.com/Informasjonsforvaltning/fdk-portal/assets/50879748/e6f71339-36d6-4211-815f-1ca0b647a82b)
