### ISSUE TITLE
BUG: "Åpne data" missing from filter-boxes

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-portal#1986]
## 🐛 Bug rapport

<img width="402" alt="image" src="https://github.com/Informasjonsforvaltning/fdk-portal/assets/48259307/c068d1a0-30b0-4e80-859b-48adf5b9de14">

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by jeffreiffers** [comment]
Jeg ser åpne data i filter boksen. Kan denne lukkes?
