### ISSUE TITLE
BUG(Dataset): testing av new.staging mot staging

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-portal#2011]
## 🐛 Bug rapport
- Funn:
  - [x] Informasjonsforvaltning/fdk-search-service#166
- Eksisterende feil: 
  - [ ] GET til user feeback skal ikke utføres når brukeren ikke er pålogget. 
  - [ ] støtter ikke felt fra dcat standarden: spatial geogerafisk avgrensning
  - [ ] Avgrensninger: viser til en blank node. Eksempel: se dataset 'Dyphavsundersøkelser Data'

- OK: 
  - sortering
  - filter
  - nullstilling av filtre
  - paginrering (gjelder Alle fanen med fokus på Dataset)

**Comment by NilsOveTen** [comment]
new.staging har blitt stengt ned og koden er prodsatt
