### ISSUE TITLE
BUG: detaljsiden, "Dette begrepet er ikke omtalt i Datalandsbyen" vises ikke i new.staging

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#2014]
### Nåværende oppførsel
new.staging
![image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/108797958/13a55a5b-0144-41a8-9fd7-0d095f7a9b07)

Sidemeny til venstre:
![Image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/110605570/7d4c5946-f370-49d2-b806-0b71b6bb13a7)

### Forventet oppførsel
staging
![image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/108797958/378737f4-412f-4b41-80cb-5d8b88898af8)

Sidemeny til venstre: 
![Image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/110605570/50fd6e2c-614d-4750-8afc-8c2d916b43a5)

### Hvordan reprodusere?
Besøk for eksempel https://new.staging.fellesdatakatalog.digdir.no/concepts/d328cd31-6c17-4721-a298-10ed9440f5d2

Gjelder også de andre katalogene. Denne saken skal derfor fikse problemet for 
- [ ] Informasjonsmodeller
- [ ] Tjenestekatalogen
- [ ] Begrepskatalogen
- [ ] Datasettkatalogen
- [ ] API-katalogen

**Comment by KjerstiSteien** [comment]
Se også https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/928
