### ISSUE TITLE
BUG: Det mangler et ord i "Har du spørsmål eller .."-menyfeltet i alle detaljsider

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-portal#2015]
### Nåværende oppførsel
Ny portal mangler et ord på detaljside (dette gjelder for samtlige ressurstyper), ref "Har du spørsmål eller kommentarer til ?":
![bilde](https://github.com/Informasjonsforvaltning/fdk-portal/assets/8625716/64a0e38c-ed43-497c-a4a3-fefe23eec3cf)

**Comment by terjesyl** [comment]
Relatert til https://github.com/Informasjonsforvaltning/fdk-portal/issues/2013
og
