### ISSUE TITLE
BUG: partitiv (og assosiativ) relasjon vises ikke

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-portal#2016]
## 🐛 Bug rapport

https://new.staging.fellesdatakatalog.digdir.no/concepts/b30e8df5-ab28-3607-bbfa-f1961e4f8cfb

![image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/48259307/1cf08dcd-c0d6-4f3f-b2fc-512af029421f)
![image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/48259307/d8934026-2695-4ad5-87ed-c9246e5fddd3)

**Comment by terjesyl** [comment]
I staging:
Begrepsbeskrivelsen ser ut til å ha blitt endret i databasen, den har nå ingen partitiv relasjon i respons-objektet, men kun assosiativ relasjon. Denne vises hverken i new.staging eller i staging Denne feilen gjelder også assosiativ relasjon, men er tilstede i responsen begge steder:

![Image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/108797958/cb888f05-2c33-4a87-909e-26da5f08b7b8)

**Comment by terjesyl** [comment]
Søket til fdk-search-service gir ingen resultater på relaterte begreper:
https://search.api.staging.fellesdatakatalog.digdir.no/search/concepts

```json
{"pagination":{"size":1},"filters":{"uri":{"value":["https://concept-catalog.staging.fellesdatakatalog.digdir.no/collections/910258028/ae196a9c-def1-42da-8a9b-345e4ee47310"]}}}
```

![Image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/108797958/4174f260-bc09-48cc-8398-101ef47f7801)

**Comment by terjesyl** [comment]
Andre begreper derimot får respons på samme type spørring:

```curl
curl 'https://search.api.staging.fellesdatakatalog.digdir.no/search/concepts' -X POST -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Origin: http://localhost:3001' -H 'Connection: keep-alive' -H 'Referer: http://localhost:3001/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers' --data-raw '{"pagination":{"size":7},"filters":{"uri":{"value":["https://concept-catalog.staging.fellesdatakatalog.digdir.no/collections/312460726/concepts/6ef5ec25-537e-4a86-80df-163da5488ed1","https://concept-catalog.staging.fellesdatakatalog.digdir.no/collections/910244132/concepts/75f229c6-dff7-4c0e-a08e-8010391751a4","https://concept-catalog.staging.fellesdatakatalog.digdir.no/collections/910244132/concepts/ebc804e7-d55a-46e5-954a-6397c0ea044e","https://concept-catalog.staging.fellesdatakatalog.digdir.no/collections/910244132/concepts/a292ce07-134b-48ff-b149-ced63aaea87f","https://concept-catalog.staging.fellesdatakatalog.digdir.no/collections/910244132/concepts/60c5d846-a8b6-4546-a0db-95569e94b50b","https://concept-catalog.staging.fellesdatakatalog.digdir.no/collections/312460726/concepts/6ef5ec25-537e-4a86-80df-163da5488ed1","https://concept-catalog.staging.fellesdatakatalog.digdir.no/collections/974760673/concepts/831d5c6d-f710-4ffe-a30b-f2ec9525d0f5"]}}}'
```
