### ISSUE TITLE
BUG: To begrep med samme id men ulik identifikator

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-portal#2017]
https://staging.fellesdatakatalog.digdir.no/concepts/f6e9ace1-0588-4545-8ba8-b371d7def75b

https://new.staging.fellesdatakatalog.digdir.no/concepts/f6e9ace1-0588-4545-8ba8-b371d7def75b

![image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/48259307/453634ae-8fb7-46e7-9fa8-d2c125087ede)

**Comment by NilsOveTen** [comment]
dette ser ut til å være samme issue som https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/927

**Comment by NilsOveTen** [comment]
ble løst av ny høsting
