### ISSUE TITLE
Sorteringsknapper

### ISSUE THREAD

**Issue by oyvindis** [Informasjonsforvaltning/fdk-portal#207]
Skal fungere på lik linje som de andre katalogene
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/all/search-all-default.html

**Comment by lillelars** [comment]
frontend på plass. venter på backend før jeg lukker denne.

**Comment by lillelars** [comment]
Fungerer som forventet. Lukker derfor denne nå.
Testet i chrome og edge
