### ISSUE TITLE
"Alle"-fane : mangler to filtermuligheter

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#213]
Mangler filter for:
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/all/search-all-default.html
- [x] Tilgangsnivå for Datasett

- [x] Tilgangsnivå for API'er

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/b586a2a4-2f32-43aa-bbae-3529270dc3f4)

**Comment by lillelars** [comment]
Filter for API på alle-fane fungerer ikke og viser feil filterinformasjon over filtermeny.
![image](https://user-images.githubusercontent.com/39513382/80076172-108e6e80-854c-11ea-9584-e3a8e3f34f1f.png)

**Comment by rannveigskjerve** [comment]
> @rannveigskjerve @oyvindis hvem bør ta denne? Setter tilbake til arbeid.
> 
>     * [ ]  Filter for API på alle-fane fungerer ikke
 Den her er min ser det ut som. Får en eller annen server error. Den andre tror jeg er @oyvindis si, men det ordner seg kanskje med fix fra BE?


Ser ut som det ji

**Comment by rannveigskjerve** [comment]
@oyvindis : var visst ikke BE likevel. Requesten som sendes in  mangler "" på verdi . før øyeblikket er det `{"filters":[{"isFree":true}]}`, men må være [{"isFree": "true" }]}`. Tar meg selv av issuet og setter det på Øyvind igjen  😅

**Comment by lillelars** [comment]
Testet i chrome, i staging - fungerer nå som forventet.
