### ISSUE TITLE
BUG: Manglende mellomrom for visning av tittel på andre språk

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-portal#2144]
Se feks her: https://data.norge.no/concepts/71081281-7f5f-3a7a-a278-b2700b87e6ea

Visning av nynyorsk og engelsk står veldig tett hvis du har valgt bokmål som språk:
![Screenshot 2024-09-30 at 09 41 13](https://github.com/user-attachments/assets/c97ceb5a-b680-4afe-977a-cbea1ca0f748)

Et lite skille mellom de to bør legges til

**Comment by KurtStian** [comment]
Dublett til: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1009
