### ISSUE TITLE
Oppdateringer design datasettdetaljeside

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#234]
- [ ] Begrensent tilgang: Ikonet mangler symbolet inni hengelåsen. (se design: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-restricted-default.html)
![image](https://user-images.githubusercontent.com/39513382/83148331-1e11b800-a0f9-11ea-9028-459c5d8b8e57.png)

- [x] Tilgang: Mener at teksten skal være «Kan deles offentlig» (ikke «Offentlig data»). 

- [x] Bakgrunnsfarge for begrenset offentlighet, unntatt offentlighet og "offentlig" , denne tilgangen skal være dataset-light (#D5E1F2). (altså alle bortsett fra "ÅPNE DATA"):
![image](https://user-images.githubusercontent.com/39513382/83148599-7a74d780-a0f9-11ea-8d2d-f23b81d85ae9.png)

- [x] Distribusjoner: Øk padding slik at boksen blir luftigere. I skissene er det brukt padding 15px 30px.

**Comment by oyvindis** [comment]
Fra Lene:
Totalt sett opererer vi altså med tre farger og er konsekvent på det:
Åpne data:  dataset-dark
Kan deles offentlig:  dataset-light
Begrenset offentlighet:  hvit
Unntatt offentlighet:  hvit

**Comment by oyvindis** [comment]
Ikonet må vente, det må lages på nytt for å kunne endre farge spesifikt for symbol i midten.

**Comment by lillelars** [comment]
Godkjenner denne uten ikon.
Opprettet nytt issue for ikon: #387 

Lukker denne.
