### ISSUE TITLE
UU-krav: Oppdateringer for å tilfredstille UU 

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#235]
Farge på begrepsikon + titler:

- [x] Farge: Endre concept-dark til #2E6773

- [x] Ikon ![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/39c2440e-dd80-485a-b3dc-6a89ca5c77da)

- [x] Titler 
![image](https://user-images.githubusercontent.com/39513382/79538093-ed634b00-8083-11ea-916d-4171e443a54c.png)

- [x] Endre farge på skrift og pil brødsmulesti til: neutral-darker.
![image](https://user-images.githubusercontent.com/39513382/79538136-09ff8300-8084-11ea-87e6-21299fe554d3.png)

- [ ] <html> element does not have a [lang] attribute

- [x] duplikat id-er

**Comment by rannveigskjerve** [comment]
**sjekke feil automatisk:**

1. installer [axe accessibility checker i chrome](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd)
2. restart browser
3. åpne developer console
4. gå til "axe" fanen og trykk analyze
5. velg "violations" i menyen til venstre

**Comment by lillelars** [comment]
lene har sjekket og talt :)  Får ingen feilmeldinger på test av UU nå. Lukker derfor denne.
