### ISSUE TITLE
Mangler filter på "Åpne data" for alle fane

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#237]
Se på filter for "tilgangsnivå for datasett" på alle fanen:
her forventer jeg å se samme filter som på datasettfanen som inkluderer "åpne data"
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/f51bf261-69e9-4033-82a0-91a9a70d9ecf)

**Comment by oyvindis** [comment]
Filteret vil komme automatisk hvis det blir lagt på en aggregation 'opendata' i endepunktet, likt som i datasett-endepunkt:

opendata: {
 doc_count: 995
}

**Comment by rannveigskjerve** [comment]
Må legges til filter i request body, `{
	"filters": [{"opendata":"true"}]
}`

**Comment by lillelars** [comment]
Filteret fungerer nå som det skal. Testet i chrome i staging og dmeo
