### ISSUE TITLE
Håndtering av URLer ved bytte til data.norge.no

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#244]
- [ ] Hvordan håndtering av URL'er når vi bytter domenet... Hvordan håndterer vi dette? Redirect var ikke bra nok ift endepunktene Politiet fikk ikke tak i bankAPIene (?)

- [ ] Stig sjekker hvordan Politiet legger ann? Løsningen vi sette ropp må vi også passe på at fungerer for Politiet.

**Comment by lillelars** [comment]
Setter denne på dere to @valosnah  og @stigbd .. vi må ganske snart finne ut om vi må gjøre en jobb ifm dette

**Comment by valosnah** [comment]
[ ] - Få sertifikater for data.norge (*.staging.data.norge.no, *.demo.data.norge.no, *.data.norge.no
[ ] - Legge inn sertifikatene
[ ] - Endre ingress til å peke mot nye domener
[ ] - Endre reverse-proxy i brreg-clusteret til å peke mot nytt domene (ifbm politiet)
[ ] - Sette opp plan for varsling om overgang

**Comment by valosnah** [comment]
Hvordan vil vi gjøre dette med de forskjellige tjenestene?
fellesdatakatalog.digdir.no -> data.norge.no
organization-catalogue.fellesdatakatalog.digdir.no -> organization-cataloge.data.norge.no ?

**Comment by lillelars** [comment]
@stigbd vi trenger en rask avklaring på om kommentarene over stemmer.

**Comment by stigbd** [comment]
Vi må dokumentere alle disse. Det er ikkje trivielt og tar litt tid. Strengt tatt bør vi lage ein tabell der kolonne A er eksisterande url, og kolonne B er evt nye url.

**Comment by valosnah** [comment]
registrering.fellesdatakatalog.digdir.no  -> registrering.data.norge.no
www.fellesdatakatalog.digdir.no -> www.data.norge.no
nap.fellesdatakatalog.digdir.no -> nap.data.norge.no
registrering-begrep.fellesdatakatalog.digdir.no - > registrering-begrep.data.norge.no
registrering-begrep-api.fellesdatakatalog.digdir.no -> registrering-begrep-api.data.norge.no
harvester.fellesdatakatalog.digdir.no -> harvester.data.norge.no
sso.fellesdatakatalog.digdir.no -> sso.data.norge.no
admin.fellesdatakatalog.digdir.no -> admin.data.norge.no
admin-api.fellesdatakatalog.digdir.no -> admin-api.data.norge.no
admin-broker.fellesdatakatalog.digdir.no -> admin-broker.data.norge.no
fellesdatakatalog.digdir.no -> data.norge.no
organization-catalogue.fellesdatakatalog.digdir.no -> organization-catalogue.data.norge.no 
registrering-protokoll.fellesdatakatalog.digdir.no -> registrering-protokoll.data.norge.no 
data.transportportal.no -> (ingen endring)
dataservice-publisher.digdir.no -> dataservice-publisher.data.norge.no
dataservices.fellesdatakatalog.digdir.no -> dataservices.data.norge.no
search.fellesdatakatalog.digdir.no -> search.data.norge.no
datasets.fellesdatakatalog.digdir.no -> datasets.data.norge.no
dataservice-catalog.fellesdatakatalog.digdir.no -> dataservice-catalog.data.norge.no

staging og demo-linkene som idag (dvs staging og demo mellom tjeneste og data.norge.no, feks admin-api.demo.data.norge.no)

**Comment by valosnah** [comment]
Jeg har bestilt sertifikater for data.norge.no, men jeg trenger en bekreftelse på at vi går videre med disse URL'ene før jeg kan bestille DNS records

**Comment by valosnah** [comment]
- [x] Bestille/få sertifikater for *.norge.no
- [ ] Legge inn sertifikatene
- [ ] Endre ingress til å håndtere nye domener
- [ ] Legge til omdirigering av kall som ikke kommer via data.norge.no
- [ ] Legge til reverse-proxy mot oss selv på nye URL'er

**Comment by lillelars** [comment]
Lenker mot portal er på plass. Lukker denne.
