### ISSUE TITLE
Vise artikler på ulike språk

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#250]
i praksis må vi skrive nyheter på ulike språk som helt uavhengige nyhetsartikler.  Deretter må spørringene  mot APIet lgege på et filter som henter ut innhold på rett språk...

For eksempel:
[08.58] Dingsøyr, Sture
    T.d. så hentar de no ut nyhende på framsida slik: 

https://cms-fellesdatakatalog.digdir.no/api/content/node/news?fields[node--news]=title,field_ingress,created,changed,langcode&page[limit]=3&sort=-created
​[08.58] Dingsøyr, Sture
    Om de legg på filter slik:

https://cms-fellesdatakatalog.digdir.no/api/content/node/news?fields[node--news]=title,field_ingress,created,changed,langcode&page[limit]=3&sort=-created&filter[langcode]=nb
​[08.59] Dingsøyr, Sture
    Så vil APIet returnere berre nyhende på bokmål
​[08.59] Dingsøyr, Sture
    Eller en, nn for engelsk og nynorks

[09.00] Dingsøyr, Sture
    Når ein redaktør opprettar ei nyhende så kan denne sette kva språk innhaldselementet skal vere på...dette skjer i skjemaet her:

![image](https://user-images.githubusercontent.com/39513382/79837106-3f241200-83b1-11ea-90b3-a6b0d4dd7a03.png)

​[09.01] Dingsøyr, Sture
    I døme på filterspørring så la eg og med felt for språk slik at de kan sjå det som felt i JSON outputen...

https://cms-fellesdatakatalog.digdir.no/api/content/node/news?fields[node--news]=title,field_ingress,created,changed,langcode&page[limit]=3&sort=-created&filter[langcode]=nb

**Comment by lillelars** [comment]
@joebrreg @stigbd Denne må vi ta en prat om hvordan vi skal håndtere.. 
Ref :
"selv om det er ulogisk at det blir ulike uttrekk basert på språk. Ser vel for meg at ikke alle gidder å publisere alle nyheter på nb og nn. Da blir det kanskje færre nyheter på nynorsk. Og hvis vi gjør uttrekk med både nb og nn så blir det mange duplikate nyheter for de nyhetene som eventuelt publiseres både med nb og nn.

Dvs. det er egentlig bare en riktig måte å gjøre dette på og det er at det kan publiseres på flere språk i samme artikkel, så kan man velge visningsspråk i uttrekket."

**Comment by KjerstiSteien** [comment]
Regnes som løst. Vi støtter redaksjonelle sider på ulike språk i dag og vil fortsette med det fremover. Per i dag har vi ikke nyhetssider lenger, så den delen er ikke relevant lenger.
