### ISSUE TITLE
Datasett detaljeside: Feil Avgrensninger og klarer ikke slå opp Norge

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#269]
testet i prod, chrome:

- [ ] 1) Her burde vi klare å slå opp og at det skal stå "Norge"

- [x] 2) Her skal det stå "Tidsmessig avgrenset til:"

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/a3fa151a-faa7-483c-b9a2-0d3ef94e4785)
![image](https://user-images.githubusercontent.com/39513382/80184499-fcf60d00-860a-11ea-977d-e369f5539ae8.png)

**Comment by azaxarov** [comment]
@lillelars, det ser ut som geonorge har endret URIen sine

Fra: http://data.geonorge.no/administrativeEnheter/nasjon/id/173163
Til: https://data.geonorge.no/administrativeEnheter/nasjon/doc/173163

Det er mulig at vår høster klarer ikke å plukke opp endringer, så det har ingenting med protal å gjøre. Eneste portalen forventer er en prefLabel. I dette tilfellet, så er det ingenting der.
