### ISSUE TITLE
Artikkelsiden - bilde feil plassert

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#270]
Fra CMS-systemet:
![image](https://user-images.githubusercontent.com/39513382/80215734-39daf780-863d-11ea-9a40-dd5254eedb65.png)

Se: https://staging.fellesdatakatalog.digdir.no/news/53216cde-044f-4270-a4a4-e6ac6f8a24df
Forventer at bilde skal være plassert under teksten der det ble lagt i CMS'et..

Fra CMS:
![image](https://user-images.githubusercontent.com/39513382/80185944-7ee73580-860d-11ea-9bd9-8c009df51a2d.png)

**Comment by oyvindis** [comment]
@lillelars : avklart denne med Sture, må endres i artikkelpublisering i CMS.

Bildet i artikkelen er publisert som en egen modul uavhengig av brødtekst. Ihht. design viser vi dette som et toppbilde i full bredde.

Det er to valg for å legge til bilde:
1: Inne i brødteksten
 
2: Som eigen modul uavhengig av brødtekst

Vel ein alternativ 1, kan ein style bilda med float for få flytande tekst rundt bildet.

**Comment by lillelars** [comment]
Etter prat med Øyvind og Sture, endrer jeg beskrivelsen over.. Har også republisert artikkelen i tre moduler:
brødtekst 
image
brødtekst

**Comment by lillelars** [comment]
Nå blir bildet plassert riktig.
