### ISSUE TITLE
Verdi i "Identifikator" burde vise identifikatoren til begrepet i "kilden"

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-portal#287]
Verdi i "Identifikator"-feltet burde vere identifikator slik den er oppgitt i det endepunktet som høstes, ikkje den identifikatoren som fkd tildeler ved høsting. Dvs i staden for å vise verdien i "uri":
`https://fellesdatakatalog.digdir.no/api/concepts/5cd09fd8-0ac9-494a-b49e-3fa68ef9bb30 `
burde dette feltet vise verdien av "identifier":
`http://data.brreg.no/begrep/32686`
![Screenshot from 2020-04-28 20-22-04](https://user-images.githubusercontent.com/1702357/80523287-1b069900-898e-11ea-8e21-05aeb1678b3b.png)

**Comment by oyvindis** [comment]
@stigbd . F.eks. begrep i prod: https://fellesdatakatalog.digdir.no/concepts/158987e8-93b8-4b83-8326-49481d5d5f93

hvis jeg viser lenke som verdien av feltet 'identifier' så er det til registreringsløsning: https://registrering-begrep-api.fellesdatakatalog.digdir.no/974760223/ce5f9853-2494-4bc5-ae7f-6848e9955c1d

Er det det du mener?

**Comment by stigbd** [comment]
Ja.

(Men eksempelet du viser til er dårlig. Vi burde i registreringsløysinga bruke ein anna identifier. Ein som i prinsippet kan nås. Men det blir i eit anna issue, på registreringsløysinga.)

**Comment by lillelars** [comment]
Testet av Stig i prod :) lukker denne.
