### ISSUE TITLE
Korriger stavemåten til "Felles datakatalog"

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-portal#307]
Kan dere rette opp, fra "Felles Datakatalog" (med stor D) til "Felles datakatalog" (med liten d)?

Dette gjelder: 

- Meny-knappen for "Om Felles Datakatalog" 
- På siden https://fellesdatakatalog.digdir.no/about,  i hvert fall i "Ingressen" og i "brødstien".  

Fra: @jimjyang

**Comment by joebrreg** [comment]
@lillelars Har vi ikke en oppgave som går på menypunktene nå? Da kan vi ta med denne.

**Comment by lillelars** [comment]
Denne er fikset. Lukker saken.
