### ISSUE TITLE
[Informasjonsmodell] Verdi i "Identifikator" burde vise identifikatoren til informasjonsmodell i "kilden" 

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-portal#309]
Verdi i "Identifikator"-feltet burde vere identifikator slik den er oppgitt i det endepunktet som høstes, ikkje den identifikatoren som fkd tildeler ved høsting. Dvs i staden for å vise verdien i "id":
https://demo.difi.no/api/informationmodels/8bfa055a-9b0c-40df-a7c2-2e58173eb2e0
burde dette feltet vise verdien av "identifier":
https://raw.githubusercontent.com/Informasjonsforvaltning/model-publisher/master/src/model/model-catalog.ttl#PersonOgEnhet

**Comment by joebrreg** [comment]
Testet ok: https://demo.fellesdatakatalog.digdir.no/informationmodels/d1115536-2fd6-4bde-be29-240bad171a3b
