### ISSUE TITLE
Oppdatere "Hjelp til å registrere"

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#332]
Får tekst fra Joachim

**Comment by joebrreg** [comment]
@oyvindis Den første lenken peker feil. Den går til Altinn og ikke registreringsløsning:
"Her finner du katalogene til din virksomhet i Felles datakatalog: https://registrering.fellesdatakatalog.digdir.no"

**Comment by lillelars** [comment]
Denne går nå korrekt. Lukker saken
