### ISSUE TITLE
Extract og load alle Open API specifications fra data.norge.no

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#361]
Open-API-specs for datahotellet er no på eige Github-repo:
https://github.com/datahotellet/oas

Disse må legges i riktige kataloger

**Comment by KjerstiSteien** [comment]
@livarb fortsatt relevant?

**Comment by livarb** [comment]
Her er det ei løype å gå før ein kan gjere noo.
Tenker denne kan lukkast i utviklingsbrettet til fordel for ei sak i behovsbrettet.
Der har vi ei sak frå før: https://github.com/Informasjonsforvaltning/behov/issues/666

Tittelen er noko misvisande. Dette handlar om genererte OAS-spesifikasjonar for datasett registrert i data.norge.no som peikar til datasett på datahotellet.
Må børste støv av scriptet som genererer OAS (er knytt til gamle data.norge-plattformen) og finne ut korleis ein kan få dette inn i data.norge.no.
