### ISSUE TITLE
Utvide rapport-siden vår

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#375]
Vi må også utvide slik at Transportportal.no får Rapportsider for datasett.

Se her:
https://eggedosis.github.io/fdk-design/redirects/portal/transport/report-default.html

**Comment by lillelars** [comment]
@joebrreg Denne kan vi kanskje lukke snart?

**Comment by joebrreg** [comment]
@lillelars Er alle boogers fiksa?
