### ISSUE TITLE
Datasett detaljesiden: Feil ikon for begrenset offentlighet

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#387]
Korrekt ikon:

- [x] Begrensent tilgang: Ikonet mangler symbolet inni hengelåsen. (se design: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-restricted-default.html)
![image](https://user-images.githubusercontent.com/39513382/83148331-1e11b800-a0f9-11ea-9028-459c5d8b8e57.png)

**Comment by LeneSundsbo** [comment]
@jeffreiffers 
[Her er lenke til ikon](https://drive.google.com/file/d/19-gmqSWSggTOfV1VBR3zIx_rifeX4Efh/view?usp=sharing), som ser sånn ut (med strek inni):

<img width="321" alt="Screenshot 2022-03-11 at 12 35 18" src="https://user-images.githubusercontent.com/25385497/157859587-2b780fc0-9936-4e5b-83ad-29ae599048a2.png">
