### ISSUE TITLE
Feil på ikoner detaljside API

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-portal#408]
![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/3569e850-b135-4aff-a33a-197ae740233d)

Eksempel fra Chrome. Vises også feil i Firefox.
Det gjelder Gratis osv.

**Comment by lillelars** [comment]
Denne gjelder ikke lenger ettersom vi har nytt design. Lukker saken.
