### ISSUE TITLE
Utforsk hvorvidt organization catalog kan gjøre oppslag mot enhetsregisteret

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#417]
- [x] Undersøke enhetsregisterAPI - hva er mulighetene for søk

- [ ] dersom organisasjonsnr ikke finnes i organzation catalog vil det gjøres et oppslag mot enhetseregisteret. Dette nr vil også bli lagret i organization catalog ved treff i enhetsregisteret.

- [ ] bug på å copy/paste et orgNr - bør også være mulig

Fra Alex: 
https://data.brreg.no/enhetsregisteret/api/docs/index.html#enheter-sok

**Comment by azaxarov** [comment]
Enhetsregisteret API med mulighet for søk: https://data.brreg.no/enhetsregisteret/api/docs/index.html#enheter-sok

**Comment by lillelars** [comment]
Testet og implementert. Mangler underenheter, som vi håndterer i eget epos/issue
