### ISSUE TITLE
Felter fra ny datatjeneste-høster vises ikke i portal

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-portal#425]
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/dataservice/search-default.html

- [x] endpoint description - Endepunktsbeskrivelse
- [x] endpoint url - EndepunktURL
- [x] mediatype - Mediatyper
- [x] serves dataset - Tilknyttede datasett

**Comment by lillelars** [comment]
Disse vises nå i portal korrekt. lukker saken.
