### ISSUE TITLE
Manglende visning av begrep

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-portal#432]
Under klassen Kontaktinformasjon i Fellesmodell for Person og Enhet, har du blant annet egenskapene telefonnummer og mobiltelefonnummer. Begrepet for mobiltelefonnummer vises, men ikke for telefonnummer.

 ![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/9b6ce05a-51e9-4ced-bd4c-6d9918e308fb)
https://data.norge.no/informationModels/8bfa055a-9b0c-40df-a7c2-2e58173eb2e0

![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/73e64cfb-ecb1-484e-9239-072cf45f3504)
https://data.norge.no/api/informationmodels/8bfa055a-9b0c-40df-a7c2-2e58173eb2e0

**Comment by lillelars** [comment]
@oyvindis @azaxarov  <- kan en av dere se på denne dersom dere har tid. Ikke context-switch, men ta det når det blir tid.

**Comment by joebrreg** [comment]
Testet ok av @ToHelland.
