### ISSUE TITLE
Viser felter i datatjenester som ikke finnes

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-portal#455]
- [x] viser "Spesifikasjon" uten at det er lagt til endepunktbeskrivelse
- [x] viser "Kontaktinformasjon" i venstre meny uten at det er lagt til

**Comment by oyvindis** [comment]
Begge disse feilene er pga. endpoints og contactinfo får "example.com" hvis url-felt i registreringsløsning er registrert som blanke felt.

**Comment by NilsOveTen** [comment]
> Begge disse feilene er pga. endpoints og contactinfo får "example.com" hvis url-felt i registreringsløsning er registrert som blanke felt.

I så fall er det noe som bør fikses i dataservice-catalog, jeg ser på det

**Comment by lillelars** [comment]
Dette fungerer nå som forventet. Lukker saken.
