### ISSUE TITLE
Mangler i visning på datatjeneste detaljside

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-portal#456]
- [x] viser ikke "Tilknyttede datasettbeskrivelser"

- [ ] viser ikke "Standard (tjenestetype)"

- [ ] viser ikke egendefinert mediatype (dropper dette inntil videre)

- [x] kontaktpunkt er ikke klikkbart når kontaktpunkt url er oppgitt

- [x] viser ikke telefonnummer

Eksempel: https://staging.fellesdatakatalog.digdir.no/dataservices/827a7ffa-c171-3432-85dd-17dd7c56f831

**Comment by lillelars** [comment]
Viser nå alle felt korrekt.
"Standard (tjenestetype)" - håndtert i egen issue. Lukker dermed denne.
