### ISSUE TITLE
Lenke i demomiljø går mot Prod

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#464]
Lenke fra "hjelp"-> "Hjelp til å registrere" også denne skal i DEMO miljø gå mot en lik side som eksisterer i demo:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/3aed9b4d-d9d2-4a0a-a176-c85f1013e133)

**Comment by stigbd** [comment]
Denne må vi sjå i samanheng med issuet vi oppretta angåande ny "registreringsportal". Dette issuet finn eg ikkje, dessverre.

**Comment by valosnah** [comment]
Det er slik i staging også. Foreslår å legge opp til at denne er en miljøvariabel i alle tre miljøene.

**Comment by lillelars** [comment]
Artikler til demo miljø:
Navn BOKMÅL:
Hjelp til å registrere - dem
"type": "node--page",
"id": "4ce5c558-d98e-48b7-bc01-9997b8d1ad80",
"links": {"self": {"href": "https://cms-fellesdatakatalog.digdir.no/api/content/node/page/4ce5c558-d98e-48b7-bc01-9997b8d1ad80?resourceVersion=id%3A855"
Navn NYNORSK:
Hjelp til å registrera - Demo
"type": "node--page",
"id": "612007c4-9e66-4161-be5e-e1af60051e83",
"links": {"self": {"href": "https://cms-fellesdatakatalog.digdir.no/api/content/node/page/612007c4-9e66-4161-be5e-e1af60051e83?resourceVersion=id%3A856"
Navn Engelsk:
Help to register - Demo
"type": "node--page",
"id": "1b1e13b2-fb7b-4cea-9c2b-fd38b264bef2",
"links": {"self": {"href": "https://cms-fellesdatakatalog.digdir.no/api/content/node/page/1b1e13b2-fb7b-4cea-9c2b-fd38b264bef2?resourceVersion=id%3A857"

**Comment by shenluna** [comment]
Verifisert OK
