### ISSUE TITLE
Informasjonsmodeller har feil koblinger til datatjenester

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#468]
- [ ] Legge til koblinger fra Informasjonsmodell til datatjenester (ble fjernet i issuet: https://github.com/informasjonsforvaltning/fdk-portal/issues/604)

- [ ] Fikse buggen som gjør at vi viser alt for mange datatjenestekoblinger i hytt og gevær ![image](https://user-images.githubusercontent.com/39513382/91961943-2be46400-ed0c-11ea-97d4-8a31d604d90a.png)

**Comment by oyvindis** [comment]
HarvestSourceUri i informationmodel, finne hvilket felt i dataservice som det referer til. Antar "endpointDescription" eller "endpointURL", men ikke funnet noen faktiske match i prod.

**Comment by ToHelland** [comment]
Dette gjelder vel modeller som er generert i forbindelse med høsting av  API? I så fall er det kanskje  @stigbd som kan svare på det?
