### ISSUE TITLE
Feilmelding for detaljvisning av API-beskrivelser høstet fra DCAT-AP-NO v2

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/fdk-portal#470]
I demo-miljøet, har høstet en DCAT-fil med beskrivelse av fire datatjenester. For tre av tjenestene får jeg feilmeldingene som jeg har limt inn nedenfor når jeg forsøker å få opp detaljvisningen

De som ikke virker:
- eBevis Production, https://demo.fellesdatakatalog.digdir.no/dataservices/188ef031-489f-3e81-bab6-bb4e338bf1e3
- tittelen, https://demo.fellesdatakatalog.digdir.no/dataservices/10ddb35e-508f-3f75-9061-fb76812087fa
- Nordic Smart Government Reference API, https://demo.fellesdatakatalog.digdir.no/dataservices/302370d8-4ccb-3989-bd97-492f2e27dbbb

Den som virker: 
- Nøkkeltall fra årsregnskapet, https://demo.fellesdatakatalog.digdir.no/dataservices/ce4b4282-aced-32c2-9287-1a83e2e08072

Feilmeldingen: 
![image](https://user-images.githubusercontent.com/5012227/91971574-b67f9000-ed19-11ea-9e96-b41b327f8e4c.png)

DCAT-filen: https://raw.githubusercontent.com/brreg/openAPI/master/specs/API-catalog.ttl

De aktuelle datatjenestene:
![image](https://user-images.githubusercontent.com/5012227/91971467-859f5b00-ed19-11ea-94df-d01c80b7dca9.png)

Feilen skyldes muligens feil i vår DCAT-fil, men har åpnet issue hos dere etter avtale med @stigbd

**Comment by lillelars** [comment]
Denne er nå fikset. testet i demo og prod.
