### ISSUE TITLE
Mangler kobling fra API-beskrivelse til informasjonsmodell

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/fdk-portal#478]
API-beskrivelsen for "Åpne data fra Enhetsregisteret" mangler kobling til informasjonsmodellen.

API-beskrivelsen: https://data.norge.no/dataservices/5d521611-91da-4b4c-839e-ed7ca14f9251

Informasjonsmodellen: https://data.norge.no/informationModels/4bf0d2d6-0f30-44b5-ae2b-56108944da8e 
(men nå viser den ikke noe informasjon lenger ... sist jeg var innom så jeg informasjonsmodellen ...)

**Comment by lillelars** [comment]
@sskagemo Tok bare 6 måneder det så var denne løst :) 
Relasjonene vises under "Andre som relaterer til ......."
