### ISSUE TITLE
Informasjon om API-er mangler på detaljsidene

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/fdk-portal#479]
Følgende informasjon er ikke lenger synlig om API-er i API-katalogen
- Om et API er autoritativt
- Om API-et er Åpent for alle
- Om API-et er gratis
- Om API-et har en åpen lisens
- Status for API-et (under utprøving, avviklet etc)
- Operasjoner i API-et og tilhørende sammendrag
- Tjenestetype - (eget issue)

**Comment by KjerstiSteien** [comment]
@livarb er dette fortsatt relevant? Eller er det fikset?

**Comment by KjerstiSteien** [comment]
Lukker denne saken. De egenskapene som dekkes av ny versjon av dcat-ap-no, vil tas opp når vi jobber med å implementere støtte for denne.
