### ISSUE TITLE
Design issues - Rapportsiden

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#495]
Se design: https://eggedosis.github.io/fdk-design/redirects/portal/report/all.html
Se design NAP: https://eggedosis.github.io/fdk-design/redirects/portal/transport/report-default.html

Etter prioritet:

- [x] Tittel: Tittel har fått ny plassering (se skisser). Pass på at det ikke blir for mye luft mellom header og tittel. (gjelder NAP og FDK)

- [x] Knapp: «Nullstill alle filter» ser ut til å ha feil styling (feil farge og tekststørrelse). Riktig farge for tag: neutral-darkest #121619 (gjelder NAP og FDK)
![image](https://user-images.githubusercontent.com/39513382/93178442-8cc06300-f734-11ea-8367-d8b06bbc02aa.png)

- [x] Faner: Valgt fane skal ikke ha fargefyll men være grå slik som bakgrunnsfargen. Husk å endre bakgrunnsfarge for ikonet også.

- [x] Bokser: Reduser til 10 px mellomrom mellom alle bokser ~~(også horisontalt mellomrom)~~. (gjelder NAP og FDK)

Mellomrommet horisontalt fungerer ikke å spesifisere eksakt med piksel. Boksene flyter helt ut i kant, og skal også fungere dynamisk med tre bokser etterhvert når metadata er klart.
![image](https://user-images.githubusercontent.com/39513382/93178645-cd1fe100-f734-11ea-8656-bc8694667113.png)

- [x] Graf: Kan kakediagram roteres 90 grader slik at de starter øverst? 
![image](https://user-images.githubusercontent.com/39513382/93178980-56cfae80-f735-11ea-9b7f-319cbcecfabf.png)

- [x] Filter: Filter har feil farge, skal ha samme farge som søkeboksen over.
![image](https://user-images.githubusercontent.com/39513382/93179160-94343c00-f735-11ea-9af2-a7a8f4be3cdd.png)

- [x] Hover: Hover på rapportelementer skal være enda mørkere, neutral-darkest #121619.

- [x] Faner: Savner hover-effekt på fanene.

- [x] Antall virksomheter: Ønsker at denne skal være egen boks plassert som nr 3 fra toppen (etter utvikling) . Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/report/all.html

- [x] Antall kataloger: Ønsker at denne står som egen boks (uten antall virksomheter) med tittelen «Antall datasettkataloger». Se design nederst: https://eggedosis.github.io/fdk-design/redirects/portal/report/all.html

**Comment by oyvindis** [comment]
Bokser: Reduser til 10 px mellomrom mellom alle bokser (også horisontalt mellomrom). (gjelder NAP og FDK):
Mellomrommet fungerer ikke å spesifisere eksakt med piksel. Boksene flyter helt ut i kant, og skal også fungere dynamisk med tre bokser etterhvert når metadata er klart.

**Comment by lillelars** [comment]
Denne er nå fikset og prodsatt. Lukker saken.
