### ISSUE TITLE
Metadatakvalitet - forklaring dimensjoner - legge til '?' med hovertekst

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#509]
se design:
https://www.figma.com/proto/LNZcZ406JNnINt6phaec5b/Companies?node-id=31%3A11039&viewport=636%2C182%2C0.5400004982948303&scaling=min-zoom

Ikonet du trenger ligger her:
https://www.dropbox.com/s/b8qb6kto73bcyo3/icon-question-sm.svg?dl=0

- [ ] Ønsker å få lagt på dette ikonet, med hover: 
![image](https://user-images.githubusercontent.com/39513382/94691453-98fe1000-0331-11eb-984d-43d73c8d9088.png)

Søkbarhet: "Første steg for å benytte data er å finne den. Metadata og data skal være enkelt å finne både for mennesker og maskiner."

Tilgjengelighet: "Metadata og data kan deles og utveksles maskinelt via åpne, veldefinerte grensesnitt og formater."

Interoperabilitet: "Metadata og data er beskrevet og dokumentert med utgangspunkt i standarder."

Gjenbruk: "Metadata og data er beskrevet godt nok til at innholdet enkelt lar seg vurdere og gjenbruke."

Lesbarhet: "Metadata og data er representert på en brukervennlig og forståelig måte."

**Comment by azaxarov** [comment]
@lillelars Som diskutert på møte i dag, så blir det lite plass i tabellen for disse spørsmålsikonene. Kunne vi kanskje kun vise total metadatakvalitet på datasetskatalogsiden og heller ha forklaring på forskjellige dimensjonene på datasettsiden? Kunne du ta opp design issue med Lene?

**Comment by matsjs** [comment]
@lillelars Skal hjelpetekstene kun være tilgjengelig på norsk bokmål, eller kan jeg finne/lage translations til dem?
Og har vi en svg for de ikonene gjemt noe sted?

**Comment by lillelars** [comment]
@matsjs ikonet du trenger ligger her:
Ikonet du trenger ligger her:
https://www.dropbox.com/s/b8qb6kto73bcyo3/icon-question-sm.svg?dl=0

Angående translations har vi ikke det enda.... Men om du oppretter de for engelsk/nynorsk så kan du selv velge om du vil gjøre en best effort eller bare bruke bokmål tekstene.
- Det vil bli gjort et oversettelsesarbeid - det henger bare litt etter

**Comment by lillelars** [comment]
@matsjs Dette er ganske bra! Kunne vi ha prettyfiet mouse-over boksen litt så den blir noe mer kvadratisk? (Tips se mouse-over på skissene, EVNT se mouse-over på "Åpne data" i løsningen.
![image](https://user-images.githubusercontent.com/39513382/95381236-24eed980-08e8-11eb-9308-14c1b83592cc.png)

vs 

![image](https://user-images.githubusercontent.com/39513382/95381417-6b443880-08e8-11eb-9481-00774c54e775.png)

**Comment by lillelars** [comment]
Denne fungerer nå som forventet. Lukker saken. Testet i chrome, i staging.
