### ISSUE TITLE
Regel 4 i lesbarhet fungerer ikke som den skal

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#525]
Dersom beskrivelsen har tittelen i seg skal denne regelen trigge.

- [x] Tekst påfrontend må også endres!

![image](https://user-images.githubusercontent.com/39513382/94659175-2c205100-0304-11eb-9373-bfe33362b121.png)

Se eksempel på datasett:
https://staging.fellesdatakatalog.digdir.no/organizations/910258028/datasets/6c566377-bc0e-3dee-b446-7f5f7632b87a

**Comment by azaxarov** [comment]
Slik var regelen definert:

```
Regel 4 (Readability.descriptionWithoutTitle):
Beskrivelsen er ikke en gjentakelse av tittel.
Vekt: 5
```

Det har ingenting å gjøre med at beskrivelse inneholder tittel - bare at de to er ikke like. Kan du dobbeltsjekke @lillelars ?

**Comment by lillelars** [comment]
"Tittelen er ikke en del av beskrivelsen." @azaxarov

**Comment by lillelars** [comment]
Denne fungerer som den skal nå. Lukker saken.
