### ISSUE TITLE
FORBEDRING detaljside: Legge til en "Til toppen"-funksjon i bunnen av innholdet

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#539]
Vi ønsker en "Til toppen"-funksjon slik at det blir enkelt å navigere til toppen, samtidig som det blir tydelig at man har nådd slutten av innholdet.

https://projects.invisionapp.com/share/FWBFRNSAM#/screens/338885979

NB! Gjelder for alle faner

**Comment by KjerstiSteien** [comment]
@LeneSundsbo @jeffreiffers kan vi lukke denne og heller lage ny sak om vi ser behov for dette?

**Comment by LeneSundsbo** [comment]
Knappen er nå lagt til i de oppdaterte versjonene av detaljsiden, så da kan vi i alle fall lukke denne saken.
