### ISSUE TITLE
Modellkatalog - navnerom modellkatalog for Digitaliseringsdirektoratet

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-portal#542]
Navnerommet i filen (https://github.com/Informasjonsforvaltning/model-publisher/blob/master/src/model/model-catalog.ttl) med modellene for Enhet og Person og Adresse, har navnerommet: 
"@prefix digdir: <https://raw.githubusercontent.com/Informasjonsforvaltning/model-publisher/master/src/model/model-catalog.ttl#"> . Dette gjør at modellen og elementene får id'er basert på disse. 

For Person og Enhet får f.eks. modellen (i strukturvisningen) id: https://raw.githubusercontent.com/Informasjonsforvaltning/model-publisher/master/src/model/model-catalog.ttl#PersonOgEnhet

Bør ha et litt mer "offisielt" navnerom og id'er, som ikke begynner på https://raw.githubusercontent.com.

**Comment by azaxarov** [comment]
@lillelars Er denne issue fortsatt relevant?

**Comment by ToHelland** [comment]
Dette får vi ikke løst ennå. Digdir må komme opp med noe gode URI'er, men klarer ikke å enes. Så denne får vi ikke gjort noe med nå.

**Comment by KjerstiSteien** [comment]
Lukker denne, og ser om behovet dukker opp igjen.
