### ISSUE TITLE
Feilretting: Felles modellkatalog - begrepsreferanse på fødselsdato vises ikke 

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-portal#543]
I modellen Felles informasjonsmodell for Person og Enhet vises ikke begrepsreferansen på attributtet "fødselsdato" til objekttypen "Person". Begrepsreferansen ligger inne på attributtet i filen som høstes, https://github.com/Informasjonsforvaltning/model-publisher/blob/master/src/model/model-catalog.ttl. Går jeg til begrepet fødselsdato i begrepskatalogen, vises modellen på dette. 
Litt rart, siden det fungerer for andre modellelementer med begrepsreferanser.

**Comment by azaxarov** [comment]
@lillelars Er denne issue fortsatt relevant?

**Comment by jeffreiffers** [comment]
Dette ser ut til å være løst.


![Image](https://github.com/Informasjonsforvaltning/fdk-portal/assets/430997/951c1348-9f1b-415f-baca-2a0a00ad9ed1)
