### ISSUE TITLE
Bug - Kan ikke tabbe ut av menyknappen i header

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-portal#597]
Man kan tabbe seg inn i "Meny"/ "Språk" dropdownen, men ikke ut igjen. Dette kan være et accessibilityproblem for keyboardbrukere.

**Comment by KjerstiSteien** [comment]
Ser ut som denne er løst. Enig @jeffreiffers ?

**Comment by hegeaal** [comment]
Ser ut til at dette er løst, ja.
