### ISSUE TITLE
Oppdatere Detaljesider med korrekt terminologi på eier/ansvarlig/tilbyder

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#633]
Datasett:
Eier

Begrep:
Ansvarlig

Datatjeneste:
Tilbyder

Informasjonsmodell:
Ansvarlig

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/7f363915-b8e4-48b8-b52b-396fe46dd810)

**Comment by lillelars** [comment]
@azaxarov jeg dreit meg ut - det skal være "Ansvarlig" på informasjonsmodell også.... Kan du fikse dette på detaljesiden til informasjonsmodell?

**Comment by shenluna** [comment]
Detaljsiden for Informasjonsmodeller må oppdateres med riktig terminologi (ansvarlig)
