### ISSUE TITLE
[Bug] Kun 10 av 22 begreper vises på datasett subject

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-portal#647]
Datasettet har 22 begreper knytta til seg i dct:subject, men kun 10 vises i detaljside. Eksempel:
https://data.norge.no/datasets/68d08f28-a16d-4fab-a953-ed4ab08ce2e2

![image](https://user-images.githubusercontent.com/1702357/99043962-4a2dd200-258f-11eb-9bae-2cba601d5b19.png)

**Comment by shenluna** [comment]
Verified in Prod
![image](https://user-images.githubusercontent.com/73637969/99664534-9a61d400-2a68-11eb-8bd3-e75625321fd8.png)
