### ISSUE TITLE
Frontend: Viser ikke arvede elementer

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#66]
"Person"-objektet arver fra et annet objekt. Dette kommer frem i speccen:

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/1ac38e53-7cb0-4375-9da8-fa08b45fe6cc)

Men vises ikke i frontend:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/277b8dac-d44d-48d5-8567-33c47d0169ab)

Forventer at det ser slik ut (fra design):
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/ce72d9aa-79e3-4faa-b4a8-e81ad672a5bd)

**Comment by oyvindis** [comment]
Endre backend:
"isSubClassOf" på "Node" må være et objekt med properties "id" og "name".

Endre frontend:
vise scroll link med referanse til "id" og label "name".

**Comment by lillelars** [comment]
Fungerer nå for interne modeller. Eksterne arvinger må håndteres utenom. Lukker derfor denne nå.
Testet OK i chrome i staging.
