### ISSUE TITLE
modelldcatno:CatalogRecord - skal ikke være med i RDF-serialiseringene

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-portal#664]
Se modell i staging-miljøet, https://staging.fellesdatakatalog.digdir.no/informationmodels/bcbe6738-85f6-388c-afcc-ef1fafd7cc45.

Trolig må vi endre i backendløsningen hos oss for å ikke levere ut dette feltet: 

I de ulike visningen av RDF-serialiseringer, visningen har det sneket seg inn et element <https://informationmodels.staging.fellesdatakatalog.digdir.no/informationmodels/bcbe6738-85f6-388c-afcc-ef1fafd7cc45>, av type dcat:CatalogRecord. Dette ligger ikke i filen som høstes. dcat:CatalogRecord brukes heller ikke i ModellDCAT-AP-NO.

Inneholder
![image](https://user-images.githubusercontent.com/17720749/100868512-ff232280-349b-11eb-8155-cc13bc5961ea.png)

**Comment by lillelars** [comment]
Denne er ikke med lenger. Testet i prod, i chrome.
