### ISSUE TITLE
Informasjonsmodeller - dct:format

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-portal#665]
Se modell https://staging.fellesdatakatalog.digdir.no/informationmodels/bcbe6738-85f6-388c-afcc-ef1fafd7cc45 i staging-miljøet. dct:hasFormat vises ikke (er beskrevet i trådskisse):
![image](https://user-images.githubusercontent.com/17720749/100869588-8ae97e80-349d-11eb-92fd-f5a9acc4cac4.png)

digs:AlternativModellformat
        a           owl:NamedIndividual , <https://informasjonsforvaltning.github.io/modelldcat-ap-no/images/ModellDCAT-ap-no.png> , foaf:Document ;
        dct:format  <http://publications.europa.eu/resource/authority/file-type/PNG> ;
        dct:title   "Forenklet modell for ModellDCAT-AP-NO"@nb .

![image](https://user-images.githubusercontent.com/17720749/100869726-ba988680-349d-11eb-9f30-53e8b8649f41.png)

Trådskisse:
![image](https://user-images.githubusercontent.com/17720749/100869995-30045700-349e-11eb-861f-34fab06f0645.png)

**Comment by azaxarov** [comment]
Gjelder denne fortsatt @ToHelland @lillelars ?

**Comment by joebrreg** [comment]
Testet ok
