### ISSUE TITLE
Informasjonsmodell - lenker knyttet til søkeord.

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-portal#666]
Søkeordene på informasjonsmodellene har en lenke knyttet til seg. 

Se f.eks. https://staging.fellesdatakatalog.digdir.no/informationmodels/90096759-a1e5-376a-a7e4-0e964266d3fc:

![image](https://user-images.githubusercontent.com/17720749/100870650-45c64c00-349f-11eb-8832-1b94f9fd736e.png)
Når du klikker på disse, kommer du til en oversiktside over modeller.

Søkeordene skal ikke ha lenker, da de er av type tekst:
dcat:keyword       "Barnepass"@nb , "Innberettning"@nb ;

**Comment by ToHelland** [comment]
Jeg forsto på @lillelars at dette var et filter på alle informasjonsmodeller med det søkeordet i seg. Så det er OK, men filteret er satt feil.

**Comment by lillelars** [comment]
Duplikatsak - håndteres i https://github.com/informasjonsforvaltning/fdk-issue-tracker/issues/97
