### ISSUE TITLE
Informasjonsmodell - Relasjoner til andre modeller

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-portal#667]
Nå ser det ut til at de viser korrekt navn, men bruker får en feil ved trykk på relasjonen:
![image](https://user-images.githubusercontent.com/39513382/105460763-8e72d800-5c8c-11eb-85ba-b1996dd6e966.png)

Se f.eks. https://staging.fellesdatakatalog.digdir.no/informationmodels/bcbe6738-85f6-388c-afcc-ef1fafd7cc45:

Lenkene til de andre modeller er ikke aktive.

![image](https://user-images.githubusercontent.com/17720749/100872883-c8043f80-34a2-11eb-814d-86a3e6936275.png)

I henhold til trådskissene skal de vises slik:
![image](https://user-images.githubusercontent.com/17720749/100873248-495bd200-34a3-11eb-9a88-9e3162ae07a1.png)

**Comment by shenluna** [comment]
Denne fungere ikke per dags dato trolig pga en av disse grunnene:
- fulltext search finner ikke relaterte infomodeller
- ES index
- query som sendes fra fdk-portal

**Comment by lillelars** [comment]
@ToHelland @shenluna  Har vi noe tilfeller i demo/prod hvor vi har en slik relasjon?

**Comment by ToHelland** [comment]
@lillelars @shenluna I tillegg til fellesmodellene har vi Kartverkets modell, https://staging.fellesdatakatalog.digdir.no/informationmodels/5b15202c-ae33-35a5-aeaa-2692b9a75ec6 og SKDs, https://staging.fellesdatakatalog.digdir.no/informationmodels/90096759-a1e5-376a-a7e4-0e964266d3fc i staging.

**Comment by lillelars** [comment]
@matsjs har du tid til å se på denne også?
![image](https://user-images.githubusercontent.com/39513382/105460853-ab0f1000-5c8c-11eb-8eb0-e5146b7ea341.png)

Nå vises relasjonsnavn riktig igjen, men jeg får en feilmelding ved trykk på denne.

**Comment by shenluna** [comment]
Legge til to-veis relasjoner
feks. https://www.staging.fellesdatakatalog.digdir.no/informationmodels/cbed13d0-1b9d-36c3-a565-4b05db5fb5ea

![image](https://user-images.githubusercontent.com/73637969/106437560-b07f0e00-6475-11eb-99fa-88203fd68f4f.png)
Infomodellene som blir lenket til skal ha 'Er del av' og 'Erstattes av'

**Comment by lillelars** [comment]
Håndterer siste del av denne i nytt issue https://github.com/informasjonsforvaltning/fdk-issue-tracker/issues/178
