### ISSUE TITLE
Nyheter vises ikke på fremsiden - it's a feature

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#669]
Vi henter og viser nå de siste 3 nyhetene.
Det vi bør gjøre er å hente og vise de siste 3 PUBLISERTE nyhetene. Dersom de siste 3 er avpublisert viser vi nå ingenting:
Bør kunne gå ann å bruke et filter:
https://cms-fellesdatakatalog.digdir.no/api/content/node/news?filter[status]=1

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/08abbffb-e465-4e80-b9ae-ed2b1f33344c)

**Comment by shenluna** [comment]
Testet i staging og verifisert i prod.
![image](https://user-images.githubusercontent.com/73637969/101000389-24786500-355e-11eb-9293-a0b4d3716313.png)
