### ISSUE TITLE
Mangler klikkbarhet i strukturvisning

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#672]
F.eks skal "DatoKlokkeslett" ta bruker ned til enkelttypen "DatoKlokkeslett"

(legg på URI, hvis ikke denne finnes bruk dct:identifier)

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/c1643715-66b8-4e41-8193-7c779bcb9702)

**Comment by azaxarov** [comment]
@matsjs Dette er vel konsekvensen av at identifiers er ikke lenger tilgjengelig på noen modell elementer. Tror det går an å bruke uri i stedet.

**Comment by lillelars** [comment]
Fungerer i staging. Testet i chrome. Saken er lukket :D
