### ISSUE TITLE
feil ikon for assoiasjonselementer

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#697]
Skal i følge designet bare være en strek: " - " ved assosiasjon. 
Se design: 
https://eggedosis.github.io/fdk-design/redirects/portal/infomodel/detail-structure-default.html

Det som er benyttet nå er en "arv"-ikon. Ref:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/bb080574-2c34-4e1b-b391-c0e85ac3b00d)

**Comment by shenluna** [comment]
Testet i staging med https://www.staging.fellesdatakatalog.digdir.no/informationmodels/0bf6b09f-e1c0-3415-bba0-7ff2edada89d
![image](https://user-images.githubusercontent.com/73637969/103903266-f86f7700-50fb-11eb-998f-34a78cea0e67.png)
