### ISSUE TITLE
Utvide modellen med ex-composition og ex-collection

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#698]
Vi har nesten bygd opp støtte for ex-composition og ex-collection.
Nå må vi vise dette korrekt.
 
Se modellen: 
https://staging.fellesdatakatalog.digdir.no/informationmodels/cbed13d0-1b9d-36c3-a565-4b05db5fb5ea
og se elementene:
"Gris" - (ex-composition)
"Fruktkurv" - (ex-collection) 

Se skisser:
https://eggedosis.github.io/fdk-design/redirects/portal/infomodel/sketch-tormod-structure.html

**Comment by shenluna** [comment]
Testet i staging
