### ISSUE TITLE
Utvide infomodeller med ex-mch og ex-valgfri

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#699]
Utvide modellen med ex-mch og ex-valgfri.
Dette er nesten implementert.

Se skisser: 
https://eggedosis.github.io/fdk-design/redirects/portal/infomodel/sketch-tormod-structure.html

Se modellen:
https://staging.fellesdatakatalog.digdir.no/informationmodels/cbed13d0-1b9d-36c3-a565-4b05db5fb5ea

For feltene: 

Godtepose - (ex-mch)
Oppgave - (Ex-valgfri)

**Comment by shenluna** [comment]
Testet i staging
