### ISSUE TITLE
Utvide infomodeller med ex-bidir (assosiasjon)

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#700]
Vi skal utvide modellen med feltet ex-bidir
Se design: 
https://eggedosis.github.io/fdk-design/redirects/portal/infomodel/sketch-tormod-structure.html

Se eksempelmodell:
https://staging.fellesdatakatalog.digdir.no/informationmodels/cbed13d0-1b9d-36c3-a565-4b05db5fb5ea

Under elementet "Kreditor"

**Comment by lillelars** [comment]
@azaxarov Denne kan vi ta til slutt...

**Comment by shenluna** [comment]
Testet i staging
![image](https://user-images.githubusercontent.com/73637969/106107833-b60fe780-6147-11eb-9169-b32f3983bacd.png)
