### ISSUE TITLE
Virksomhetssiden viser feil tall på datasett og datatjenester

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#714]
Se https://data.norge.no/organizations og søk på f.eks skatteetaten:

mulig at det er SPARQL spørringer mot datasett som feiler.

(trolig er det bare beskrivelsene våre som kommer fra vår registreringsløsning som ikke blir plukket opp her.)

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/05cfe8fc-1b52-437a-8185-3b0db18e532d)

**Comment by shenluna** [comment]
Testet i staging
