### ISSUE TITLE
Endre listeikoner til infomodell strukturvisning fra Unicode til SVG

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-portal#731]
Ikoner -> https://eggedosis.github.io/fdk-design/menu.html
Design -> https://www.figma.com/proto/nrqaa1JB8pY6pBvUBxp1EV/Detail-infomodel?node-id=1012%3A2547&viewport=569%2C244%2C0.27625539898872375&scaling=min-zoom

**Comment by shenluna** [comment]
Testet i staging.
