### ISSUE TITLE
Relasjon mellom tjenester skal vises på begge sider

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#732]
F.eks:
Tjenesten: https://data.norge.no/public-services/6ce4e524-3226-3591-ad99-c026705d4259
KREVER: 
https://data.norge.no/public-services/d5d0c07c-c14f-3741-9aa3-126960958cf0

Da må den siste tjenesten også vise en relasjon tilbake. 
"Er krevd av"

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/f716ea2b-90b7-4426-b534-d552dfa7492e)

**Comment by shenluna** [comment]
Testet i staging
![image](https://user-images.githubusercontent.com/73637969/106431600-ca1c5780-646d-11eb-9f7d-53c93fc02f46.png)
