### ISSUE TITLE
Visning av LOS-tema mangler på sammendragsbokser

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#736]
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/dataset/search-default.html

Eksempel:
Her ser vi at denne datasettbeskrivelsen har LOS-temaer.
https://data.norge.no/datasets/084e2617-0e10-3578-9568-68c15ce9a1f9

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/836c617d-9571-4f01-bf39-126d57f9da96)

**Comment by shenluna** [comment]
Testet i staging
![image](https://user-images.githubusercontent.com/73637969/105704194-b5d8d780-5f0e-11eb-8930-46a80ccc0d6e.png)
