### ISSUE TITLE
Meny mangler plutselig i transportportalen

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#745]
https://data.transportportal.no/datasets/
vs
https://data.transportportal.no/datasets

gjør at filter-menyen forsvinner.

![image](https://user-images.githubusercontent.com/39513382/106143483-1d8f5c80-6173-11eb-9b0a-7d6bbd1c99a3.png)

**Comment by valosnah** [comment]
Issuet oppstår om man går til data.transportportal.no/datasets/
data.transportportal.no/datasets fungerer fint. 
Er nok en liten felle i fdk-nginx-search som gjør at menyen ikke dukker opp.

**Comment by valosnah** [comment]
Lagt inn 301 for alle tilfeller av trailing /

**Comment by lillelars** [comment]
Da fungerer dette i prod. Takk for rask fiks!
