### ISSUE TITLE
Informasjonsmodell - feil rekkefølge på kode (skos:notation) og kodetekst (skos:prefLabel) for visning av kodeliste

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-portal#750]
Feil rekkefølge, https://staging.fellesdatakatalog.digdir.no/informationmodels/665d7f6a-f6fd-3c6b-ade3-d3152ba171d1:
![image](https://user-images.githubusercontent.com/17720749/106460350-81779500-6493-11eb-8a23-16db09207317.png)

Riktig, jf. trådskisse:

![image](https://user-images.githubusercontent.com/17720749/106460203-41181700-6493-11eb-8abe-ce186f9b56ce.png)

**Comment by shenluna** [comment]
Testet i staging
![image](https://user-images.githubusercontent.com/73637969/106746206-80c13900-6622-11eb-98fe-3697d44cfc09.png)
