### ISSUE TITLE
Søk med 'Ukjent'-filter i tjenester gir ingen treff

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#755]
Per dags dato finnes det 6 tjenester uten oppgitt tilbyder
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/e6b341a9-a283-4759-a9a3-cb95b648ca28)
Når man setter på filteret for 'Ukjent', gir søket ingen svar.
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/1e978551-f229-4f9a-884d-401d27e823ff)

**Comment by stigbd** [comment]
Feilen her består i at tilbyder (hasCompetentAuthority) som er obligatorisk, ikkje er utfyllt i disse tilfellene. Spørsmålet er då korleis vi skal håndtere at denne propertien mangler.

**Comment by shenluna** [comment]
Denne gir fremdeles ingen treff når man klikker på 'Ukjent' under tilbyder.
Url-en man får opp når man klikker på 'ukjent' viser dette: https://www.staging.fellesdatakatalog.digdir.no/public-services?orgPath=MISSING

**Comment by shenluna** [comment]
Testet i Staging
