### ISSUE TITLE
Relasjon til hendelse for sammendragsboks til tjenester

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#765]
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/service/search-test-scenario.html

- [x]  Ved klikk skal det settes et filter på denne hendelsen.

**Comment by shenluna** [comment]
Når man velger to filtere får man ingen treff
![image](https://user-images.githubusercontent.com/73637969/109170253-e5366a80-7780-11eb-81ba-d19142ea0322.png)

**Comment by shenluna** [comment]
Testet i staging

**Comment by shenluna** [comment]
Verifisert i prod
