### ISSUE TITLE
Implement cache busting of static assests

### ISSUE THREAD

**Issue by azaxarov** [Informasjonsforvaltning/fdk-portal#766]
User should be able to see latest changes without needing to perform a hard refresh of the page.

The only time static assets generated by Webpack should be cached if there were no changes made to them.

**Comment by stigbd** [comment]
The goal of this issue is to forever get rid of the error in the screen dump attached.
![image](https://user-images.githubusercontent.com/1702357/107375066-a057d600-6ae8-11eb-81d5-6f2a15d28fde.png)

**Comment by shenluna** [comment]
Ikke testbar
