### ISSUE TITLE
Manglende forkortning av beskrivelser og feil farge på fade 

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-portal#771]
![Screenshot 2021-02-10 at 13.01.07.png](https://images.zenhubusercontent.com/5f748ee3d40ab48e3e1eba9f/714403c0-889e-4a12-afcb-48e95e936c28)

Gjelder både på detaljsider og i oppsummeringsbokser.

Detaljsider. Forkortning kan trigges ved å gjøre skjermvisningen smalere der det ikke vanligvis inntreffer.
- [x] Datasett: staging.fellesdatakatalog.digdir.no/datasets/338745fa-a182-43ef-8ac2-ce5cee9dd8af

- [x] Datatjenester: staging.fellesdatakatalog.digdir.no/dataservices/59a7ca14-b021-370e-9c76-ddbeb263a1f3

- [x] Begrep: staging.fellesdatakatalog.digdir.no/concepts/7dc92e76-44c6-4f2c-a2d9-1ea5a3955f83

- [x] Informasjonsmodeller: staging.fellesdatakatalog.digdir.no/informationmodels/5b15202c-ae33-35a5-aeaa-2692b9a75ec6

- [x] Tjenester: staging.fellesdatakatalog.digdir.no/public-services/487787c8-03c4-3b9d-9382-710f21219d91

**Comment by shenluna** [comment]
Testet i staging
