### ISSUE TITLE
Støtte presentasjon av Dataservice DCAT-AP 2.0 i portal

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#78]
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/dataservice/search-default.html

Frontend må forholde seg til nytt API.

- [ ] Tilpasning til ny specc (endringer i Backend)

- [ ] Tilpasning til ny specc (frontend)

- [ ] Endre fra API til Datattjeneste

- [ ] implementering av språkstøtte

**Comment by lillelars** [comment]
@stigbd @joebrreg denne er vel klar for akseptansetest.. Kan vi lukke den?

**Comment by joebrreg** [comment]
@lillelars Savner GUI. Ligger det i et annet issue?
