### ISSUE TITLE
Oppdatere detaljeside med visning på flere språk

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#795]
- [x] knapper for  språk
- [x] Oppdatere med språktags per felt der multispråk er mulig
- [x] Best-effort for mobilvisning
- [x] Hvis systemspråk settes til "Engelsk" eller "Nynorsk" skal default innhold endres til valgt systemspråk dersom det finnes. Hvis det ikke finnes skal fallback være "Bokmål"

- Som hovedregel ønsker å vise innhold og system på det språk bruker har valgt i browser
- fallback skal vise innhold på bokmål, men hvis det bare finnes på nynorsk/engelsk skal dette primært vises
- disable knapper der man ikke har flere språk

Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/concept/detail-nb-en.html
Se design ved langt begrep:
https://eggedosis.github.io/fdk-design/redirects/portal/concept/detail-long-title-nb-en.html

**Comment by shenluna** [comment]
Første begrep man går inn på er alle språkfelt grået ut
Eks:
![image](https://user-images.githubusercontent.com/73637969/114544514-08e34080-9c5b-11eb-9ffc-0bb5b411c160.png)

**Comment by oyvindis** [comment]
Oppdatert med noen fixes for fallback språk.

**Comment by shenluna** [comment]
Testet OK i staging

**Comment by shenluna** [comment]
Etter mye diskusjoner blir mye av denne saken endret og erstattet med https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/274
Lukker dermed denne saken
