### ISSUE TITLE
Nytt filter for begreper i portal på "fagområde"

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#796]
Filter for å vise de 5 mest brukte?

Kan f.eks løses lignende filter for "format" 

søk i filter?

**Comment by lillelars** [comment]
@stigbd sjekker med Jim og så tar vi denne opp om 2 uker

**Comment by stigbd** [comment]
fagområde er fritekst (rdf:Literal) ref https://data.norge.no/specification/skos-ap-no-begrep/#_begrep_fagomr%C3%A5de_tekst
Dermed egnar ikkje denne property seg til filtrering. Evt kan vi tilby søk.

Mitt forslag er å sende dette issue tilbake til behov og avvente endringar i bakanforliggande standard.

**Comment by shenluna** [comment]
Wont fix
