### ISSUE TITLE
Relasjoner som peker på meg - mangler tjeneste

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#797]
Tjenesten:
https://data.norge.no/public-services/d5d0c07c-c14f-3741-9aa3-126960958cf0

peker på datasettbeskrivelsen: 
https://data.norge.no/datasets/68d08f28-a16d-4fab-a953-ed4ab08ce2e2
og på 
https://data.norge.no/datasets/ae335ad2-0f3d-4eb1-98ce-87882776a123

MEN det vises ikke at disse tjenestene peker på dette datasettet

**Comment by shenluna** [comment]
Testet og verifisert
![image](https://user-images.githubusercontent.com/73637969/110096962-cc404180-7d9e-11eb-9915-0e1a81eaaf56.png)
