### ISSUE TITLE
Error Boundary HOC

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-portal#802]

**Comment by matsjs** [comment]
https://github.com/Informasjonsforvaltning/fdk-portal/commit/d7496b542d0994d09f81c9798587f442c3fe906c

**Comment by shenluna** [comment]
For øyeblikket ikke testbar, vil bli testet sammen med https://github.com/informasjonsforvaltning/fdk-portal/issues/808
