### ISSUE TITLE
Lage og legge til feilsider for portal v.h.a. error boundary

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-portal#808]

**Comment by shenluna** [comment]
![image](https://user-images.githubusercontent.com/73637969/110782989-1a09ed80-8268-11eb-94aa-e8ca636e74de.png)

**Comment by shenluna** [comment]
Testet OK

**Comment by shenluna** [comment]
Feilside for 500 mangler header og footer
![image](https://user-images.githubusercontent.com/73637969/111635604-f7438000-87f7-11eb-9982-0ec0bd7ab4fa.png)

**Comment by shenluna** [comment]
Feilside for 500 mangler header og footer
![image](https://user-images.githubusercontent.com/73637969/111635604-f7438000-87f7-11eb-9982-0ec0bd7ab4fa.png)

**Comment by shenluna** [comment]
Feilside for 500 mangler header og footer
![image](https://user-images.githubusercontent.com/73637969/111635604-f7438000-87f7-11eb-9982-0ec0bd7ab4fa.png)

**Comment by shenluna** [comment]
Har ikke klart å reprodusere, lukker saken
