### ISSUE TITLE
URL-er til gammel api-katalog feiler

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/fdk-portal#810]
URL-er til API-katalogen av typen 
https://data.norge.no/apis?orgPath=%2FSTAT%2F912660680%2F974760673
feiler. Nå skal det være "dataservice" istedenfor "apis" i URL-en.

Siden alle API er DataService bør det være redirect til ny URL for de som har lagret URL-er av den gamle typen.

**Comment by shenluna** [comment]
Testet og verifisert i prod
