### ISSUE TITLE
Feil i relasjoner mellom tjeneste og hendelse

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#820]
NB to oppgaver i en:

- [x] Endre overskrift på detaljeside hendelse fra "Relaterte tjeneste" til "Tjenester som inngår i hendelse"
Relatert til: https://github.com/Informasjonsforvaltning/behov/issues/446

- [x] Fikse feil i relasjoner mellom tjeneste og hendelse

Denne tjenesten "Samordnet registermelding":
https://data.norge.no/public-services/d5d0c07c-c14f-3741-9aa3-126960958cf0
har en relasjon som peker til "Starte og drive et idrettslag"
https://data.norge.no/events/d546ae30-8bb6-3f29-9e38-de7a1c4a0278

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/73492d96-d40d-40a1-9006-acaf50b84b70)

MEN "Starte og drive et idrettslag" har ingen (synlig) relasjon som peker på "Samordnet registermelding"
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/c8a4e94d-0544-42f7-ad98-363ceb73763f)

Så da spør jeg: Hvorfor har vi fått denne "relasjonen som peker på meg" i dette tilfellet?

Referanse:
https://github.com/Informasjonsforvaltning/behov/issues/462

**Comment by shenluna** [comment]
Testet OK i staging

**Comment by shenluna** [comment]
Verifisert i prod
