### ISSUE TITLE
Endre tekst for relasjoner tjeneste-hendelse

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#832]
Denne overskriften ønsker vi endret til: 'Tjenesten inngår i hendelsene'

I tillegg ønsker vi at overskriften fra hendelser blir endret til 'Tjenester som inngår i hendelsen'

![image](https://user-images.githubusercontent.com/39513382/112272181-22a4ef80-8c7c-11eb-98a9-b581b790e8c7.png)

**Comment by shenluna** [comment]
Et par endringer fra de funksjonelle.
Fra tjenester skal det stå 'Tjenesten inngår i hendelsene'
Fra hendelser skal det stå 'Tjenester som inngår i hendelsen'

**Comment by shenluna** [comment]
Verifisert i prod
