### ISSUE TITLE
Knytte Community til detaljesider

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#879]
Se design (nederst på siden):
https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-default.html

- [ ] Datasett detaljesiden

- [ ]  API detaljeside

- [ ] Begreps detaljeside

- [ ] Infomodeller detaljeside

- [ ] Tjenester og hendelser detaljeside

- [ ] Finne tråder der detaljsiden er lenket til

**Comment by matsjs** [comment]
Løses av Informasjonsforvaltning/fdk-issue-tracker#257
