### ISSUE TITLE
Virsomheter viser feil tall for antall datasett

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#881]
Kulturdepartementet har 2 datasett under virkomhetsoversikten, men 14 i portal
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/7ed61e15-985a-4471-a95e-6d79f80f650b)
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/533f9b97-5bdf-45dc-91d7-c926e64a33b4)

**Comment by NilsOveTen** [comment]
Virksomheter viser 2 datasett fordi Kulturdepartementet er direkte publisher av 2 datasett, portal viser 14 siden det er 12 datasett som er publisert av organisasjoner som ligger under Kulturdepartementet.

Begge deler er korrekt, men det blir feil å linke til orgpath-filteret fra virksomheter. Så det bør opprettes et nytt filter i portal som virksomheter kan linke til.

**Comment by shenluna** [comment]
Testet OK i staging

**Comment by shenluna** [comment]
Verifisert OK
