### ISSUE TITLE
NAP - virksomheter, feil tall på antall datasettbeskrivelser

### ISSUE THREAD

**Issue by azaxarov** [Informasjonsforvaltning/fdk-portal#884]
@lillelars commented on [Mon May 03 2021](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/301)

Viser 2, men ved klikk får jeg bare opp 1?

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/a48cddbd-f9af-445f-8e72-313d2117007d)

---

@shenluna commented on [Mon May 03 2021](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/301#issuecomment-831144294)

Samme gjelder portal, viser 2 men får opp 14 ved klikk
https://github.com/Informasjonsforvaltning/fdk-portal/issues/881

---

@NilsOveTen commented on [Mon May 03 2021](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/301#issuecomment-831183104)

Problemet for NAP-siden er at frontend ikke inkluderer filteret i spørringen
den sender en spørringen: `https://organization-bff.fellesdatakatalog.digdir.no/organizationcatalogs/972417866`
spørringen skal være: `https://organization-bff.fellesdatakatalog.digdir.no/organizationcatalogs/972417866?filter=transportportal`

**Comment by shenluna** [comment]
Verifisert OK
