### ISSUE TITLE
Lenke fra forskjellige miljøer går til andre miljøer

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#893]
I alle miljøer går det lenker til staging og prod, se bilde.

https://demo.fellesdatakatalog.digdir.no/about
https://data.norge.no/about
https://www.staging.fellesdatakatalog.digdir.no/about

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/d401bcc6-e145-4457-bcd9-9662577fe7d1)

**Comment by lillelars** [comment]
@shenluna har fikset disse for prod. Demo og staging får taes når noen påpeker det :p. Er ganske mye forvaltningsjobb i CMS'et med 3 artikler per informasjonsside per miljø

**Comment by shenluna** [comment]
Verifisert i prod. Lukker saken.
