### ISSUE TITLE
Footer i staging og demo lenker til prod

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#894]
Alle lenker under "Om felles datakatalog" i footeren i staging og demo lenker til prod.

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/ea21c367-8fce-4ab5-8d62-ddf536f7420e)

**Comment by azaxarov** [comment]
Forslag: innføre en parameter på footer som heter `baseUri` eller `fdkBaseUri` i tilfellet det kan være flere base URIer i framtiden

**Comment by jeffreiffers** [comment]
Skal dette også gjelde for Transportportal footer? Siden denne ikke brukes i staging og demo antar jeg at vi kan droppe støtte for dette på Transportportal footer.

**Comment by shenluna** [comment]
Enig med deg @jeffreiffers
Vi trenger ikke støtte for dette i Transportportalen da denne ikke brukes der.

**Comment by shenluna** [comment]
Testet OK i staging

**Comment by shenluna** [comment]
Verifisert OK
