### ISSUE TITLE
Problemer med virksomhetssiden

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#918]
Datasett viser ingen tall for noen av virksomhetene
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/25f0d58d-95d8-4e6b-bf3c-b8c27f0edb32)

Flere av detaljesidene for viksomheter er tomme og får CORS-feil 
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/23173598-8bd5-42c8-8f85-5dba63ee9697)

**Comment by valosnah** [comment]
1. sparql-service hadde blitt bombardert med oppdateringer av concepts-grafen, til det punktet at disken ble stappfull (på samme måte som den eldre løsningen slet med. Men istedet for ~1 uke skjedde dette på ~1 time)

2. sparql-service klarte ikke kjøre nattlig flush av disken lenger, siden den krever noe diskplass.

3. I forbindelse med at disken var stappfull, hadde også dataset-grafen blitt korrupt.

4. org-bff gjorde flere ting asynkront, bl.a. noe med CORS. Behandlingen av dataset-grafen kræsjet siden den var korrupt.

5. GCP/ingressen tolket responsen fra org-bff (som var en 500) som CORS-feil

**Comment by valosnah** [comment]
Midlertidig fikset ved å tømme sparql-service disken, og kjørt HarvestUpdateTrigger for samtlige datatyper

**Comment by valosnah** [comment]
Hvordan unngå samme situasjon på nytt:
Optimalt: ny løsning for hvordan vi autolagrer manuell oppdatering av begrep
Midlertidig: fdk-data-transformation-service setter en begrensning på hvor ofte den lagrer data i sparql-service

**Comment by NilsOveTen** [comment]
@stigbd Skal jeg få inn en begrensning i fdk-data-transformation-service?

**Comment by stigbd** [comment]
Ja, det er lurt. Sidan det antagelegvis tar litt tid å fikse dette på ordentlig måte. Kan du skissere her sånn ca korleis du tenker ein slik fiks vil bli gjort?

**Comment by NilsOveTen** [comment]
Vi har egentlig mange alternativer, men av de jeg klarer å tenke meg frem til så er det en jeg føler er betraktelig bedre enn de andre. Kjør transformajon ASAP etter rabbitmelding, men avvent om det kommer ny melding kort tid etterpå.

Si at vi feks har inne at den alltid avventer 15 min før den kjører ny transformasjon, tre scenarioer:
 - rabbitmelding kl 14 og kl 15 -> transformasjon og oppdatering av fuseki kl 14 og kl15
 - rabbitmelding 1400, 1402 og 1415 -> transformasjon og oppdatering av fuseki 1400, 1415 og 1500
 - rabbitmelding 1400, 1401, 1402 osv hvert minutt frem til 1500 -> transformasjon og oppdatering av fuseki 1400, 1415, 1430, 1445 og 1500

**Comment by NilsOveTen** [comment]
Satte opp issue i transformation-service: https://github.com/Informasjonsforvaltning/fdk-data-transformation-service/issues/16

**Comment by shenluna** [comment]
Datasett vises nå under virksomhetssiden. Lukker saken da Nils Ove har skilt ut det som må gjøres på transformation-service.
