### ISSUE TITLE
Vise Tilgang fra API registrering ut i portal

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#924]
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/07e0652c-3cf3-4e5f-a626-c01acacd5665)

**Comment by jeffreiffers** [comment]
Hvordan skal dette se ut?

**Comment by shenluna** [comment]
De skal vises som tags i følge designet
Se øverst, rett under tittelen: https://eggedosis.github.io/fdk-design/redirects/portal/dataservice/detail-default.html
![image](https://user-images.githubusercontent.com/73637969/128472767-348dd479-3259-4d1c-8967-df3e640cf00b.png)

**Comment by jeffreiffers** [comment]
Disse feltene er ikke eksponert som RDF og er ikke definert i DCAT-AP-NO specen. Dette må avklares før vi kan indeksere informasjonen i fulltext og vise i portalen.

**Comment by joachim-me** [comment]
Lukker denne, da dette ikke er en del av spec'en.
