### ISSUE TITLE
Fjern "Under utfasing" på EU-tema filter

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-portal#937]
Teksten "(Under utfasing) skal fjernes. Det gjelder Alle-fanen og Datasett-fanen.

![image](https://user-images.githubusercontent.com/46488929/121311121-6535aa00-c904-11eb-96c2-a631439ab6b7.png)

**Comment by shenluna** [comment]
Testet OK i staging
![image](https://user-images.githubusercontent.com/73637969/121692206-294b4200-cac8-11eb-9d12-572d88b2fb9a.png)
