### ISSUE TITLE
Fikse på design på integrasjonen mellom Datalandsbyen

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#949]
Eks
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/d064809b-53b4-4f87-9a0e-363d931c207e)

Fikse på understreken ved lange overskrifter

**Comment by matsjs** [comment]
Lukkes av https://github.com/Informasjonsforvaltning/fdk-portal/commit/0a7de84b5062d7981513e8b45a84c3e2de09cce6

**Comment by shenluna** [comment]
Testet ok, eksempel fra enhetsregisteret
![image](https://user-images.githubusercontent.com/73637969/124125112-890a8c80-da79-11eb-9b53-584eea98119e.png)
