### ISSUE TITLE
Støtte for commonmark i tekst-felter (beskrivelse) for datasett i portal

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-portal#958]
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/508

Se markdown spesifikasjon: Commonmark

**Comment by stigbd** [comment]
Implementasjon:
1. Vi må finne ein måte å serialisere commonmark til RDF,
2. Portal må deserialisere til commonmark
3. Portal presenterer det deserialiserte resultatet frå (2).

**Comment by shenluna** [comment]
Testet OK
